<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class Estados extends Seeder
{
	public function run()
	{
		$estados_insertados = $this->db->table('estados')->insertBatch([
			['id_pais' => 3, 'nombre' => 'Azerbaijan'],
			['id_pais' => 3, 'nombre' => 'Nargorni Karabakh'],
			['id_pais' => 3, 'nombre' => 'Nakhichevanskaya Region'],
			['id_pais' => 4, 'nombre' => 'Anguilla'],
			['id_pais' => 7, 'nombre' => 'Brestskaya obl.'],
			['id_pais' => 7, 'nombre' => 'Vitebskaya obl.'],
			['id_pais' => 7, 'nombre' => 'Gomelskaya obl.'],
			['id_pais' => 7, 'nombre' => 'Grodnenskaya obl.'],
			['id_pais' => 7, 'nombre' => 'Minskaya obl.'],
			['id_pais' => 7, 'nombre' => 'Mogilevskaya obl.'],
			['id_pais' => 8, 'nombre' => 'Belize'],
			['id_pais' => 10, 'nombre' => 'Hamilton'],
			['id_pais' => 15, 'nombre' => 'Dong Bang Song Cuu Long'],
			['id_pais' => 15, 'nombre' => 'Dong Bang Song Hong'],
			['id_pais' => 15, 'nombre' => 'Dong Nam Bo'],
			['id_pais' => 15, 'nombre' => 'Duyen Hai Mien Trung'],
			['id_pais' => 15, 'nombre' => 'Khu Bon Cu'],
			['id_pais' => 15, 'nombre' => 'Mien Nui Va Trung Du'],
			['id_pais' => 15, 'nombre' => 'Thai Nguyen'],
			['id_pais' => 16, 'nombre' => 'Artibonite'],
			['id_pais' => 16, 'nombre' => 'GrandAnse'],
			['id_pais' => 16, 'nombre' => 'North West'],
			['id_pais' => 16, 'nombre' => 'West'],
			['id_pais' => 16, 'nombre' => 'South'],
			['id_pais' => 16, 'nombre' => 'South East'],
			['id_pais' => 17, 'nombre' => 'Grande-Terre'],
			['id_pais' => 17, 'nombre' => 'Basse-Terre'],
			['id_pais' => 21, 'nombre' => 'Abkhazia'],
			['id_pais' => 21, 'nombre' => 'Ajaria'],
			['id_pais' => 21, 'nombre' => 'Georgia'],
			['id_pais' => 21, 'nombre' => 'South Ossetia'],
			['id_pais' => 23, 'nombre' => 'Al QÃ„Âhira'],
			['id_pais' => 23, 'nombre' => 'Aswan'],
			['id_pais' => 23, 'nombre' => 'Asyut'],
			['id_pais' => 23, 'nombre' => 'Beni Suef'],
			['id_pais' => 23, 'nombre' => 'Gharbia'],
			['id_pais' => 23, 'nombre' => 'Damietta'],
			['id_pais' => 24, 'nombre' => 'Southern District'],
			['id_pais' => 24, 'nombre' => 'Central District'],
			['id_pais' => 24, 'nombre' => 'Northern District'],
			['id_pais' => 24, 'nombre' => 'Haifa'],
			['id_pais' => 24, 'nombre' => 'Tel Aviv'],
			['id_pais' => 24, 'nombre' => 'Jerusalem'],
			['id_pais' => 25, 'nombre' => 'Bangala'],
			['id_pais' => 25, 'nombre' => 'Chhattisgarh'],
			['id_pais' => 25, 'nombre' => 'Karnataka'],
			['id_pais' => 25, 'nombre' => 'Uttaranchal'],
			['id_pais' => 25, 'nombre' => 'Andhara Pradesh'],
			['id_pais' => 25, 'nombre' => 'Assam'],
			['id_pais' => 25, 'nombre' => 'Bihar'],
			['id_pais' => 25, 'nombre' => 'Gujarat'],
			['id_pais' => 25, 'nombre' => 'Jammu and Kashmir'],
			['id_pais' => 25, 'nombre' => 'Kerala'],
			['id_pais' => 25, 'nombre' => 'Madhya Pradesh'],
			['id_pais' => 25, 'nombre' => 'Manipur'],
			['id_pais' => 25, 'nombre' => 'Maharashtra'],
			['id_pais' => 25, 'nombre' => 'Megahalaya'],
			['id_pais' => 25, 'nombre' => 'Orissa'],
			['id_pais' => 25, 'nombre' => 'Punjab'],
			['id_pais' => 25, 'nombre' => 'Pondisheri'],
			['id_pais' => 25, 'nombre' => 'Rajasthan'],
			['id_pais' => 25, 'nombre' => 'Tamil Nadu'],
			['id_pais' => 25, 'nombre' => 'Tripura'],
			['id_pais' => 25, 'nombre' => 'Uttar Pradesh'],
			['id_pais' => 25, 'nombre' => 'Haryana'],
			['id_pais' => 25, 'nombre' => 'Chandigarh'],
			['id_pais' => 26, 'nombre' => 'Azarbayjan-e Khavari'],
			['id_pais' => 26, 'nombre' => 'Esfahan'],
			['id_pais' => 26, 'nombre' => 'Hamadan'],
			['id_pais' => 26, 'nombre' => 'Kordestan'],
			['id_pais' => 26, 'nombre' => 'Markazi'],
			['id_pais' => 26, 'nombre' => 'Sistan-e Baluches'],
			['id_pais' => 26, 'nombre' => 'Yazd'],
			['id_pais' => 26, 'nombre' => 'Kerman'],
			['id_pais' => 26, 'nombre' => 'Kermanshakhan'],
			['id_pais' => 26, 'nombre' => 'Mazenderan'],
			['id_pais' => 26, 'nombre' => 'Tehran'],
			['id_pais' => 26, 'nombre' => 'Fars'],
			['id_pais' => 26, 'nombre' => 'Horasan'],
			['id_pais' => 26, 'nombre' => 'Husistan'],
			['id_pais' => 30, 'nombre' => 'Aktyubinskaya obl.'],
			['id_pais' => 30, 'nombre' => 'Alma-Atinskaya obl.'],
			['id_pais' => 30, 'nombre' => 'Vostochno-Kazahstanskaya obl.'],
			['id_pais' => 30, 'nombre' => 'Gurevskaya obl.'],
			['id_pais' => 30, 'nombre' => 'Zhambylskaya obl. (Dzhambulskaya obl.)'],
			['id_pais' => 30, 'nombre' => 'Dzhezkazganskaya obl.'],
			['id_pais' => 30, 'nombre' => 'Karagandinskaya obl.'],
			['id_pais' => 30, 'nombre' => 'Kzyl-Ordinskaya obl.'],
			['id_pais' => 30, 'nombre' => 'Kokchetavskaya obl.'],
			['id_pais' => 30, 'nombre' => 'Kustanaiskaya obl.'],
			['id_pais' => 30, 'nombre' => 'Mangystauskaya (Mangyshlakskaya obl.)'],
			['id_pais' => 30, 'nombre' => 'Pavlodarskaya obl.'],
			['id_pais' => 30, 'nombre' => 'Severo-Kazahstanskaya obl.'],
			['id_pais' => 30, 'nombre' => 'Taldy-Kurganskaya obl.'],
			['id_pais' => 30, 'nombre' => 'Turgaiskaya obl.'],
			['id_pais' => 30, 'nombre' => 'Akmolinskaya obl. (Tselinogradskaya obl.)'],
			['id_pais' => 30, 'nombre' => 'Chimkentskaya obl.'],
			['id_pais' => 31, 'nombre' => 'Littoral'],
			['id_pais' => 31, 'nombre' => 'Southwest Region'],
			['id_pais' => 31, 'nombre' => 'North'],
			['id_pais' => 31, 'nombre' => 'Central'],
			['id_pais' => 33, 'nombre' => 'Government controlled area'],
			['id_pais' => 33, 'nombre' => 'Turkish controlled area'],
			['id_pais' => 34, 'nombre' => 'Issik Kulskaya Region'],
			['id_pais' => 34, 'nombre' => 'Kyrgyzstan'],
			['id_pais' => 34, 'nombre' => 'Narinskaya Region'],
			['id_pais' => 34, 'nombre' => 'Oshskaya Region'],
			['id_pais' => 34, 'nombre' => 'Tallaskaya Region'],
			['id_pais' => 37, 'nombre' => 'al-Jahra'],
			['id_pais' => 37, 'nombre' => 'al-Kuwait'],
			['id_pais' => 38, 'nombre' => 'Latviya'],
			['id_pais' => 39, 'nombre' => 'Tarabulus'],
			['id_pais' => 39, 'nombre' => 'Bengasi'],
			['id_pais' => 40, 'nombre' => 'Litva'],
			['id_pais' => 43, 'nombre' => 'Moldova'],
			['id_pais' => 45, 'nombre' => 'Auckland'],
			['id_pais' => 45, 'nombre' => 'Bay of Plenty'],
			['id_pais' => 45, 'nombre' => 'Canterbury'],
			['id_pais' => 45, 'nombre' => 'Gisborne'],
			['id_pais' => 45, 'nombre' => 'Hawkes Bay'],
			['id_pais' => 45, 'nombre' => 'Manawatu-Wanganui'],
			['id_pais' => 45, 'nombre' => 'Marlborough'],
			['id_pais' => 45, 'nombre' => 'Nelson'],
			['id_pais' => 45, 'nombre' => 'Northland'],
			['id_pais' => 45, 'nombre' => 'Otago'],
			['id_pais' => 45, 'nombre' => 'Southland'],
			['id_pais' => 45, 'nombre' => 'Taranaki'],
			['id_pais' => 45, 'nombre' => 'Tasman'],
			['id_pais' => 45, 'nombre' => 'Waikato'],
			['id_pais' => 45, 'nombre' => 'Wellington'],
			['id_pais' => 45, 'nombre' => 'West Coast'],
			['id_pais' => 49, 'nombre' => 'Saint-Denis'],
			['id_pais' => 50, 'nombre' => 'Altaiskii krai'],
			['id_pais' => 50, 'nombre' => 'Amurskaya obl.'],
			['id_pais' => 50, 'nombre' => 'Arhangelskaya obl.'],
			['id_pais' => 50, 'nombre' => 'Astrahanskaya obl.'],
			['id_pais' => 50, 'nombre' => 'Bashkiriya obl.'],
			['id_pais' => 50, 'nombre' => 'Belgorodskaya obl.'],
			['id_pais' => 50, 'nombre' => 'Bryanskaya obl.'],
			['id_pais' => 50, 'nombre' => 'Buryatiya'],
			['id_pais' => 50, 'nombre' => 'Vladimirskaya obl.'],
			['id_pais' => 50, 'nombre' => 'Volgogradskaya obl.'],
			['id_pais' => 50, 'nombre' => 'Vologodskaya obl.'],
			['id_pais' => 50, 'nombre' => 'Voronezhskaya obl.'],
			['id_pais' => 50, 'nombre' => 'Nizhegorodskaya obl.'],
			['id_pais' => 50, 'nombre' => 'Dagestan'],
			['id_pais' => 50, 'nombre' => 'Evreiskaya obl.'],
			['id_pais' => 50, 'nombre' => 'Ivanovskaya obl.'],
			['id_pais' => 50, 'nombre' => 'Irkutskaya obl.'],
			['id_pais' => 50, 'nombre' => 'Kabardino-Balkariya'],
			['id_pais' => 50, 'nombre' => 'Kaliningradskaya obl.'],
			['id_pais' => 50, 'nombre' => 'Tverskaya obl.'],
			['id_pais' => 50, 'nombre' => 'Kalmykiya'],
			['id_pais' => 50, 'nombre' => 'Kaluzhskaya obl.'],
			['id_pais' => 50, 'nombre' => 'Kamchatskaya obl.'],
			['id_pais' => 50, 'nombre' => 'Kareliya'],
			['id_pais' => 50, 'nombre' => 'Kemerovskaya obl.'],
			['id_pais' => 50, 'nombre' => 'Kirovskaya obl.'],
			['id_pais' => 50, 'nombre' => 'Komi'],
			['id_pais' => 50, 'nombre' => 'Kostromskaya obl.'],
			['id_pais' => 50, 'nombre' => 'Krasnodarskii krai'],
			['id_pais' => 50, 'nombre' => 'Krasnoyarskii krai'],
			['id_pais' => 50, 'nombre' => 'Kurganskaya obl.'],
			['id_pais' => 50, 'nombre' => 'Kurskaya obl.'],
			['id_pais' => 50, 'nombre' => 'Lipetskaya obl.'],
			['id_pais' => 50, 'nombre' => 'Magadanskaya obl.'],
			['id_pais' => 50, 'nombre' => 'Marii El'],
			['id_pais' => 50, 'nombre' => 'Mordoviya'],
			['id_pais' => 50, 'nombre' => 'Moscow Y Moscow Region'],
			['id_pais' => 50, 'nombre' => 'Murmanskaya obl.'],
			['id_pais' => 50, 'nombre' => 'Novgorodskaya obl.'],
			['id_pais' => 50, 'nombre' => 'Novosibirskaya obl.'],
			['id_pais' => 50, 'nombre' => 'Omskaya obl.'],
			['id_pais' => 50, 'nombre' => 'Orenburgskaya obl.'],
			['id_pais' => 50, 'nombre' => 'Orlovskaya obl.'],
			['id_pais' => 50, 'nombre' => 'Penzenskaya obl.'],
			['id_pais' => 50, 'nombre' => 'Permskiy krai'],
			['id_pais' => 50, 'nombre' => 'Primorskii krai'],
			['id_pais' => 50, 'nombre' => 'Pskovskaya obl.'],
			['id_pais' => 50, 'nombre' => 'Rostovskaya obl.'],
			['id_pais' => 50, 'nombre' => 'Ryazanskaya obl.'],
			['id_pais' => 50, 'nombre' => 'Samarskaya obl.'],
			['id_pais' => 50, 'nombre' => 'Saint-Petersburg and Region'],
			['id_pais' => 50, 'nombre' => 'Saratovskaya obl.'],
			['id_pais' => 50, 'nombre' => 'Saha (Yakutiya)'],
			['id_pais' => 50, 'nombre' => 'Sahalin'],
			['id_pais' => 50, 'nombre' => 'Sverdlovskaya obl.'],
			['id_pais' => 50, 'nombre' => 'Severnaya Osetiya'],
			['id_pais' => 50, 'nombre' => 'Smolenskaya obl.'],
			['id_pais' => 50, 'nombre' => 'Stavropolskii krai'],
			['id_pais' => 50, 'nombre' => 'Tambovskaya obl.'],
			['id_pais' => 50, 'nombre' => 'Tatarstan'],
			['id_pais' => 50, 'nombre' => 'Tomskaya obl.'],
			['id_pais' => 50, 'nombre' => 'Tulskaya obl.'],
			['id_pais' => 50, 'nombre' => 'Tyumenskaya obl. i Hanty-Mansiiskii AO'],
			['id_pais' => 50, 'nombre' => 'Udmurtiya'],
			['id_pais' => 50, 'nombre' => 'Ulyanovskaya obl.'],
			['id_pais' => 50, 'nombre' => 'Uralskaya obl.'],
			['id_pais' => 50, 'nombre' => 'Habarovskii krai'],
			['id_pais' => 50, 'nombre' => 'Chelyabinskaya obl.'],
			['id_pais' => 50, 'nombre' => 'Checheno-Ingushetiya'],
			['id_pais' => 50, 'nombre' => 'Chitinskaya obl.'],
			['id_pais' => 50, 'nombre' => 'Chuvashiya'],
			['id_pais' => 50, 'nombre' => 'Yaroslavskaya obl.'],
			['id_pais' => 51, 'nombre' => 'Ahuachapán'],
			['id_pais' => 51, 'nombre' => 'Cuscatlán'],
			['id_pais' => 51, 'nombre' => 'La Libertad'],
			['id_pais' => 51, 'nombre' => 'La Paz'],
			['id_pais' => 51, 'nombre' => 'La Unión'],
			['id_pais' => 51, 'nombre' => 'San Miguel'],
			['id_pais' => 51, 'nombre' => 'San Salvador'],
			['id_pais' => 51, 'nombre' => 'Santa Ana'],
			['id_pais' => 51, 'nombre' => 'Sonsonate'],
			['id_pais' => 54, 'nombre' => 'Paramaribo'],
			['id_pais' => 56, 'nombre' => 'Gorno-Badakhshan Region'],
			['id_pais' => 56, 'nombre' => 'Kuljabsk Region'],
			['id_pais' => 56, 'nombre' => 'Kurgan-Tjube Region'],
			['id_pais' => 56, 'nombre' => 'Sughd Region'],
			['id_pais' => 56, 'nombre' => 'Tajikistan'],
			['id_pais' => 57, 'nombre' => 'Ashgabat Region'],
			['id_pais' => 57, 'nombre' => 'Krasnovodsk Region'],
			['id_pais' => 57, 'nombre' => 'Mary Region'],
			['id_pais' => 57, 'nombre' => 'Tashauz Region'],
			['id_pais' => 57, 'nombre' => 'Chardzhou Region'],
			['id_pais' => 58, 'nombre' => 'Grand Turk'],
			['id_pais' => 59, 'nombre' => 'Bartin'],
			['id_pais' => 59, 'nombre' => 'Bayburt'],
			['id_pais' => 59, 'nombre' => 'Karabuk'],
			['id_pais' => 59, 'nombre' => 'Adana'],
			['id_pais' => 59, 'nombre' => 'Aydin'],
			['id_pais' => 59, 'nombre' => 'Amasya'],
			['id_pais' => 59, 'nombre' => 'Ankara'],
			['id_pais' => 59, 'nombre' => 'Antalya'],
			['id_pais' => 59, 'nombre' => 'Artvin'],
			['id_pais' => 59, 'nombre' => 'Afion'],
			['id_pais' => 59, 'nombre' => 'Balikesir'],
			['id_pais' => 59, 'nombre' => 'Bilecik'],
			['id_pais' => 59, 'nombre' => 'Bursa'],
			['id_pais' => 59, 'nombre' => 'Gaziantep'],
			['id_pais' => 59, 'nombre' => 'Denizli'],
			['id_pais' => 59, 'nombre' => 'Izmir'],
			['id_pais' => 59, 'nombre' => 'Isparta'],
			['id_pais' => 59, 'nombre' => 'Icel'],
			['id_pais' => 59, 'nombre' => 'Kayseri'],
			['id_pais' => 59, 'nombre' => 'Kars'],
			['id_pais' => 59, 'nombre' => 'Kodjaeli'],
			['id_pais' => 59, 'nombre' => 'Konya'],
			['id_pais' => 59, 'nombre' => 'Kirklareli'],
			['id_pais' => 59, 'nombre' => 'Kutahya'],
			['id_pais' => 59, 'nombre' => 'Malatya'],
			['id_pais' => 59, 'nombre' => 'Manisa'],
			['id_pais' => 59, 'nombre' => 'Sakarya'],
			['id_pais' => 59, 'nombre' => 'Samsun'],
			['id_pais' => 59, 'nombre' => 'Sivas'],
			['id_pais' => 59, 'nombre' => 'Istanbul'],
			['id_pais' => 59, 'nombre' => 'Trabzon'],
			['id_pais' => 59, 'nombre' => 'Corum'],
			['id_pais' => 59, 'nombre' => 'Edirne'],
			['id_pais' => 59, 'nombre' => 'Elazig'],
			['id_pais' => 59, 'nombre' => 'Erzincan'],
			['id_pais' => 59, 'nombre' => 'Erzurum'],
			['id_pais' => 59, 'nombre' => 'Eskisehir'],
			['id_pais' => 60, 'nombre' => 'Jinja'],
			['id_pais' => 60, 'nombre' => 'Kampala'],
			['id_pais' => 61, 'nombre' => 'Andijon Region'],
			['id_pais' => 61, 'nombre' => 'Buxoro Region'],
			['id_pais' => 61, 'nombre' => 'Jizzac Region'],
			['id_pais' => 61, 'nombre' => 'Qaraqalpaqstan'],
			['id_pais' => 61, 'nombre' => 'Qashqadaryo Region'],
			['id_pais' => 61, 'nombre' => 'Navoiy Region'],
			['id_pais' => 61, 'nombre' => 'Namangan Region'],
			['id_pais' => 61, 'nombre' => 'Samarqand Region'],
			['id_pais' => 61, 'nombre' => 'Surxondaryo Region'],
			['id_pais' => 61, 'nombre' => 'Sirdaryo Region'],
			['id_pais' => 61, 'nombre' => 'Tashkent Region'],
			['id_pais' => 61, 'nombre' => 'Fergana Region'],
			['id_pais' => 61, 'nombre' => 'Xorazm Region'],
			['id_pais' => 62, 'nombre' => 'Vinnitskaya obl.'],
			['id_pais' => 62, 'nombre' => 'Volynskaya obl.'],
			['id_pais' => 62, 'nombre' => 'Dnepropetrovskaya obl.'],
			['id_pais' => 62, 'nombre' => 'Donetskaya obl.'],
			['id_pais' => 62, 'nombre' => 'Zhitomirskaya obl.'],
			['id_pais' => 62, 'nombre' => 'Zakarpatskaya obl.'],
			['id_pais' => 62, 'nombre' => 'Zaporozhskaya obl.'],
			['id_pais' => 62, 'nombre' => 'Ivano-Frankovskaya obl.'],
			['id_pais' => 62, 'nombre' => 'Kievskaya obl.'],
			['id_pais' => 62, 'nombre' => 'Kirovogradskaya obl.'],
			['id_pais' => 62, 'nombre' => 'Krymskaya obl.'],
			['id_pais' => 62, 'nombre' => 'Luganskaya obl.'],
			['id_pais' => 62, 'nombre' => 'Lvovskaya obl.'],
			['id_pais' => 62, 'nombre' => 'Nikolaevskaya obl.'],
			['id_pais' => 62, 'nombre' => 'Odesskaya obl.'],
			['id_pais' => 62, 'nombre' => 'Poltavskaya obl.'],
			['id_pais' => 62, 'nombre' => 'Rovenskaya obl.'],
			['id_pais' => 62, 'nombre' => 'Sumskaya obl.'],
			['id_pais' => 62, 'nombre' => 'Ternopolskaya obl.'],
			['id_pais' => 62, 'nombre' => 'Harkovskaya obl.'],
			['id_pais' => 62, 'nombre' => 'Hersonskaya obl.'],
			['id_pais' => 62, 'nombre' => 'Hmelnitskaya obl.'],
			['id_pais' => 62, 'nombre' => 'Cherkasskaya obl.'],
			['id_pais' => 62, 'nombre' => 'Chernigovskaya obl.'],
			['id_pais' => 62, 'nombre' => 'Chernovitskaya obl.'],
			['id_pais' => 68, 'nombre' => 'Estoniya'],
			['id_pais' => 69, 'nombre' => 'Cheju'],
			['id_pais' => 69, 'nombre' => 'Chollabuk'],
			['id_pais' => 69, 'nombre' => 'Chollanam'],
			['id_pais' => 69, 'nombre' => 'Chungcheongbuk'],
			['id_pais' => 69, 'nombre' => 'Chungcheongnam'],
			['id_pais' => 69, 'nombre' => 'Incheon'],
			['id_pais' => 69, 'nombre' => 'Kangweon'],
			['id_pais' => 69, 'nombre' => 'Kwangju'],
			['id_pais' => 69, 'nombre' => 'Kyeonggi'],
			['id_pais' => 69, 'nombre' => 'Kyeongsangbuk'],
			['id_pais' => 69, 'nombre' => 'Kyeongsangnam'],
			['id_pais' => 69, 'nombre' => 'Pusan'],
			['id_pais' => 69, 'nombre' => 'Seoul'],
			['id_pais' => 69, 'nombre' => 'Taegu'],
			['id_pais' => 69, 'nombre' => 'Taejeon'],
			['id_pais' => 69, 'nombre' => 'Ulsan'],
			['id_pais' => 70, 'nombre' => 'Aichi'],
			['id_pais' => 70, 'nombre' => 'Akita'],
			['id_pais' => 70, 'nombre' => 'Aomori'],
			['id_pais' => 70, 'nombre' => 'Wakayama'],
			['id_pais' => 70, 'nombre' => 'Gifu'],
			['id_pais' => 70, 'nombre' => 'Gunma'],
			['id_pais' => 70, 'nombre' => 'Ibaraki'],
			['id_pais' => 70, 'nombre' => 'Iwate'],
			['id_pais' => 70, 'nombre' => 'Ishikawa'],
			['id_pais' => 70, 'nombre' => 'Kagawa'],
			['id_pais' => 70, 'nombre' => 'Kagoshima'],
			['id_pais' => 70, 'nombre' => 'Kanagawa'],
			['id_pais' => 70, 'nombre' => 'Kyoto'],
			['id_pais' => 70, 'nombre' => 'Kochi'],
			['id_pais' => 70, 'nombre' => 'Kumamoto'],
			['id_pais' => 70, 'nombre' => 'Mie'],
			['id_pais' => 70, 'nombre' => 'Miyagi'],
			['id_pais' => 70, 'nombre' => 'Miyazaki'],
			['id_pais' => 70, 'nombre' => 'Nagano'],
			['id_pais' => 70, 'nombre' => 'Nagasaki'],
			['id_pais' => 70, 'nombre' => 'Nara'],
			['id_pais' => 70, 'nombre' => 'Niigata'],
			['id_pais' => 70, 'nombre' => 'Okayama'],
			['id_pais' => 70, 'nombre' => 'Okinawa'],
			['id_pais' => 70, 'nombre' => 'Osaka'],
			['id_pais' => 70, 'nombre' => 'Saga'],
			['id_pais' => 70, 'nombre' => 'Saitama'],
			['id_pais' => 70, 'nombre' => 'Shiga'],
			['id_pais' => 70, 'nombre' => 'Shizuoka'],
			['id_pais' => 70, 'nombre' => 'Shimane'],
			['id_pais' => 70, 'nombre' => 'Tiba'],
			['id_pais' => 70, 'nombre' => 'Tokyo'],
			['id_pais' => 70, 'nombre' => 'Tokushima'],
			['id_pais' => 70, 'nombre' => 'Tochigi'],
			['id_pais' => 70, 'nombre' => 'Tottori'],
			['id_pais' => 70, 'nombre' => 'Toyama'],
			['id_pais' => 70, 'nombre' => 'Fukui'],
			['id_pais' => 70, 'nombre' => 'Fukuoka'],
			['id_pais' => 70, 'nombre' => 'Fukushima'],
			['id_pais' => 70, 'nombre' => 'Hiroshima'],
			['id_pais' => 70, 'nombre' => 'Hokkaido'],
			['id_pais' => 70, 'nombre' => 'Hyogo'],
			['id_pais' => 70, 'nombre' => 'Yoshimi'],
			['id_pais' => 70, 'nombre' => 'Yamagata'],
			['id_pais' => 70, 'nombre' => 'Yamaguchi'],
			['id_pais' => 70, 'nombre' => 'Yamanashi'],
			['id_pais' => 73, 'nombre' => 'Hong Kong'],
			['id_pais' => 74, 'nombre' => 'Indonesia'],
			['id_pais' => 75, 'nombre' => 'Jordan'],
			['id_pais' => 76, 'nombre' => 'Malaysia'],
			['id_pais' => 77, 'nombre' => 'Singapore'],
			['id_pais' => 78, 'nombre' => 'Taiwan'],
			['id_pais' => 30, 'nombre' => 'Kazahstan'],
			['id_pais' => 62, 'nombre' => 'Ukraina'],
			['id_pais' => 25, 'nombre' => 'India'],
			['id_pais' => 23, 'nombre' => 'Egypt'],
			['id_pais' => 106, 'nombre' => 'Damascus'],
			['id_pais' => 131, 'nombre' => 'Isle of Man'],
			['id_pais' => 30, 'nombre' => 'Zapadno-Kazahstanskaya obl.'],
			['id_pais' => 50, 'nombre' => 'Adygeya'],
			['id_pais' => 50, 'nombre' => 'Hakasiya'],
			['id_pais' => 93, 'nombre' => 'Dubai'],
			['id_pais' => 50, 'nombre' => 'Chukotskii AO'],
			['id_pais' => 99, 'nombre' => 'Beirut'],
			['id_pais' => 137, 'nombre' => 'Tegucigalpa'],
			['id_pais' => 138, 'nombre' => 'Santo Domingo'],
			['id_pais' => 139, 'nombre' => 'Ulan Bator'],
			['id_pais' => 23, 'nombre' => 'Sinai'],
			['id_pais' => 140, 'nombre' => 'Baghdad'],
			['id_pais' => 140, 'nombre' => 'Basra'],
			['id_pais' => 140, 'nombre' => 'Mosul'],
			['id_pais' => 141, 'nombre' => 'Johannesburg'],
			['id_pais' => 104, 'nombre' => 'Morocco'],
			['id_pais' => 104, 'nombre' => 'Tangier'],
			['id_pais' => 50, 'nombre' => 'Yamalo-Nenetskii AO'],
			['id_pais' => 122, 'nombre' => 'Tunisia'],
			['id_pais' => 92, 'nombre' => 'Thailand'],
			['id_pais' => 117, 'nombre' => 'Mozambique'],
			['id_pais' => 84, 'nombre' => 'Korea'],
			['id_pais' => 87, 'nombre' => 'Pakistan'],
			['id_pais' => 142, 'nombre' => 'Aruba'],
			['id_pais' => 80, 'nombre' => 'Bahamas'],
			['id_pais' => 69, 'nombre' => 'South Korea'],
			['id_pais' => 132, 'nombre' => 'Jamaica'],
			['id_pais' => 93, 'nombre' => 'Sharjah'],
			['id_pais' => 93, 'nombre' => 'Abu Dhabi'],
			['id_pais' => 24, 'nombre' => 'Ramat Hagolan'],
			['id_pais' => 115, 'nombre' => 'Nigeria'],
			['id_pais' => 64, 'nombre' => 'Ain'],
			['id_pais' => 64, 'nombre' => 'Haute-Savoie'],
			['id_pais' => 64, 'nombre' => 'Aisne'],
			['id_pais' => 64, 'nombre' => 'Allier'],
			['id_pais' => 64, 'nombre' => 'Alpes-de-Haute-Provence'],
			['id_pais' => 64, 'nombre' => 'Hautes-Alpes'],
			['id_pais' => 64, 'nombre' => 'Alpes-Maritimes'],
			['id_pais' => 64, 'nombre' => 'Ardèche'],
			['id_pais' => 64, 'nombre' => 'Ardennes'],
			['id_pais' => 64, 'nombre' => 'Ariège'],
			['id_pais' => 64, 'nombre' => 'Aube'],
			['id_pais' => 64, 'nombre' => 'Aude'],
			['id_pais' => 64, 'nombre' => 'Aveyron'],
			['id_pais' => 64, 'nombre' => 'Bouches-du-Rhône'],
			['id_pais' => 64, 'nombre' => 'Calvados'],
			['id_pais' => 64, 'nombre' => 'Cantal'],
			['id_pais' => 64, 'nombre' => 'Charente'],
			['id_pais' => 64, 'nombre' => 'Charente Maritime'],
			['id_pais' => 64, 'nombre' => 'Cher'],
			['id_pais' => 64, 'nombre' => 'Corrèze'],
			['id_pais' => 64, 'nombre' => 'Dordogne'],
			['id_pais' => 64, 'nombre' => 'Corse'],
			['id_pais' => 64, 'nombre' => 'Côte dOr'],
			['id_pais' => 64, 'nombre' => 'Saône et Loire'],
			['id_pais' => 64, 'nombre' => 'Côtes dArmor'],
			['id_pais' => 64, 'nombre' => 'Creuse'],
			['id_pais' => 64, 'nombre' => 'Doubs'],
			['id_pais' => 64, 'nombre' => 'Drôme'],
			['id_pais' => 64, 'nombre' => 'Eure'],
			['id_pais' => 64, 'nombre' => 'Eure-et-Loire'],
			['id_pais' => 64, 'nombre' => 'Finistère'],
			['id_pais' => 64, 'nombre' => 'Gard'],
			['id_pais' => 64, 'nombre' => 'Haute-Garonne'],
			['id_pais' => 64, 'nombre' => 'Gers'],
			['id_pais' => 64, 'nombre' => 'Gironde'],
			['id_pais' => 64, 'nombre' => 'Hérault'],
			['id_pais' => 64, 'nombre' => 'Ille et Vilaine'],
			['id_pais' => 64, 'nombre' => 'Indre'],
			['id_pais' => 64, 'nombre' => 'Indre-et-Loire'],
			['id_pais' => 64, 'nombre' => 'Isère'],
			['id_pais' => 64, 'nombre' => 'Jura'],
			['id_pais' => 64, 'nombre' => 'Landes'],
			['id_pais' => 64, 'nombre' => 'Loir-et-Cher'],
			['id_pais' => 64, 'nombre' => 'Loire'],
			['id_pais' => 64, 'nombre' => 'Rhône'],
			['id_pais' => 64, 'nombre' => 'Haute-Loire'],
			['id_pais' => 64, 'nombre' => 'Loire Atlantique'],
			['id_pais' => 64, 'nombre' => 'Loiret'],
			['id_pais' => 64, 'nombre' => 'Lot'],
			['id_pais' => 64, 'nombre' => 'Lot-et-Garonne'],
			['id_pais' => 64, 'nombre' => 'Lozère'],
			['id_pais' => 64, 'nombre' => 'Maine et Loire'],
			['id_pais' => 64, 'nombre' => 'Manche'],
			['id_pais' => 64, 'nombre' => 'Marne'],
			['id_pais' => 64, 'nombre' => 'Haute-Marne'],
			['id_pais' => 64, 'nombre' => 'Mayenne'],
			['id_pais' => 64, 'nombre' => 'Meurthe-et-Moselle'],
			['id_pais' => 64, 'nombre' => 'Meuse'],
			['id_pais' => 64, 'nombre' => 'Morbihan'],
			['id_pais' => 64, 'nombre' => 'Moselle'],
			['id_pais' => 64, 'nombre' => 'Nièvre'],
			['id_pais' => 64, 'nombre' => 'Nord'],
			['id_pais' => 64, 'nombre' => 'Oise'],
			['id_pais' => 64, 'nombre' => 'Orne'],
			['id_pais' => 64, 'nombre' => 'Pas-de-Calais'],
			['id_pais' => 64, 'nombre' => 'Puy-de-Dôme'],
			['id_pais' => 64, 'nombre' => 'Pyrénées-Atlantiques'],
			['id_pais' => 64, 'nombre' => 'Hautes-Pyrénées'],
			['id_pais' => 64, 'nombre' => 'Pyrénées-Orientales'],
			['id_pais' => 64, 'nombre' => 'Bas Rhin'],
			['id_pais' => 64, 'nombre' => 'Haut Rhin'],
			['id_pais' => 64, 'nombre' => 'Haute-Saône'],
			['id_pais' => 64, 'nombre' => 'Sarthe'],
			['id_pais' => 64, 'nombre' => 'Savoie'],
			['id_pais' => 64, 'nombre' => 'Paris'],
			['id_pais' => 64, 'nombre' => 'Seine-Maritime'],
			['id_pais' => 64, 'nombre' => 'Seine-et-Marne'],
			['id_pais' => 64, 'nombre' => 'Yvelines'],
			['id_pais' => 64, 'nombre' => 'Deux-Sèvres'],
			['id_pais' => 64, 'nombre' => 'Somme'],
			['id_pais' => 64, 'nombre' => 'Tarn'],
			['id_pais' => 64, 'nombre' => 'Tarn-et-Garonne'],
			['id_pais' => 64, 'nombre' => 'Var'],
			['id_pais' => 64, 'nombre' => 'Vaucluse'],
			['id_pais' => 64, 'nombre' => 'Vendée'],
			['id_pais' => 64, 'nombre' => 'Vienne'],
			['id_pais' => 64, 'nombre' => 'Haute-Vienne'],
			['id_pais' => 64, 'nombre' => 'Vosges'],
			['id_pais' => 64, 'nombre' => 'Yonne'],
			['id_pais' => 64, 'nombre' => 'Territoire de Belfort'],
			['id_pais' => 64, 'nombre' => 'Essonne'],
			['id_pais' => 64, 'nombre' => 'Hauts-de-Seine'],
			['id_pais' => 64, 'nombre' => 'Seine-Saint-Denis'],
			['id_pais' => 64, 'nombre' => 'Val-de-Marne'],
			['id_pais' => 64, 'nombre' => 'Val-dOise'],
			['id_pais' => 29, 'nombre' => 'Piemonte - Torino'],
			['id_pais' => 29, 'nombre' => 'Piemonte - Alessandria'],
			['id_pais' => 29, 'nombre' => 'Piemonte - Asti'],
			['id_pais' => 29, 'nombre' => 'Piemonte - Biella'],
			['id_pais' => 29, 'nombre' => 'Piemonte - Cuneo'],
			['id_pais' => 29, 'nombre' => 'Piemonte - Novara'],
			['id_pais' => 29, 'nombre' => 'Piemonte - Verbania'],
			['id_pais' => 29, 'nombre' => 'Piemonte - Vercelli'],
			['id_pais' => 29, 'nombre' => 'Valle dAosta - Aosta'],
			['id_pais' => 29, 'nombre' => 'Lombardia - Milano'],
			['id_pais' => 29, 'nombre' => 'Lombardia - Bergamo'],
			['id_pais' => 29, 'nombre' => 'Lombardia - Brescia'],
			['id_pais' => 29, 'nombre' => 'Lombardia - Como'],
			['id_pais' => 29, 'nombre' => 'Lombardia - Cremona'],
			['id_pais' => 29, 'nombre' => 'Lombardia - Lecco'],
			['id_pais' => 29, 'nombre' => 'Lombardia - Lodi'],
			['id_pais' => 29, 'nombre' => 'Lombardia - Mantova'],
			['id_pais' => 29, 'nombre' => 'Lombardia - Pavia'],
			['id_pais' => 29, 'nombre' => 'Lombardia - Sondrio'],
			['id_pais' => 29, 'nombre' => 'Lombardia - Varese'],
			['id_pais' => 29, 'nombre' => 'Trentino Alto Adige - Trento'],
			['id_pais' => 29, 'nombre' => 'Trentino Alto Adige - Bolzano'],
			['id_pais' => 29, 'nombre' => 'Veneto - Venezia'],
			['id_pais' => 29, 'nombre' => 'Veneto - Belluno'],
			['id_pais' => 29, 'nombre' => 'Veneto - Padova'],
			['id_pais' => 29, 'nombre' => 'Veneto - Rovigo'],
			['id_pais' => 29, 'nombre' => 'Veneto - Treviso'],
			['id_pais' => 29, 'nombre' => 'Veneto - Verona'],
			['id_pais' => 29, 'nombre' => 'Veneto - Vicenza'],
			['id_pais' => 29, 'nombre' => 'Friuli Venezia Giulia - Trieste'],
			['id_pais' => 29, 'nombre' => 'Friuli Venezia Giulia - Gorizia'],
			['id_pais' => 29, 'nombre' => 'Friuli Venezia Giulia - Pordenone'],
			['id_pais' => 29, 'nombre' => 'Friuli Venezia Giulia - Udine'],
			['id_pais' => 29, 'nombre' => 'Liguria - Genova'],
			['id_pais' => 29, 'nombre' => 'Liguria - Imperia'],
			['id_pais' => 29, 'nombre' => 'Liguria - La Spezia'],
			['id_pais' => 29, 'nombre' => 'Liguria - Savona'],
			['id_pais' => 29, 'nombre' => 'Emilia Romagna - Bologna'],
			['id_pais' => 29, 'nombre' => 'Emilia Romagna - Ferrara'],
			['id_pais' => 29, 'nombre' => 'Emilia Romagna - Forlì-Cesena'],
			['id_pais' => 29, 'nombre' => 'Emilia Romagna - Modena'],
			['id_pais' => 29, 'nombre' => 'Emilia Romagna - Parma'],
			['id_pais' => 29, 'nombre' => 'Emilia Romagna - Piacenza'],
			['id_pais' => 29, 'nombre' => 'Emilia Romagna - Ravenna'],
			['id_pais' => 29, 'nombre' => 'Emilia Romagna - Reggio Emilia'],
			['id_pais' => 29, 'nombre' => 'Emilia Romagna - Rimini'],
			['id_pais' => 29, 'nombre' => 'Toscana - Firenze'],
			['id_pais' => 29, 'nombre' => 'Toscana - Arezzo'],
			['id_pais' => 29, 'nombre' => 'Toscana - Grosseto'],
			['id_pais' => 29, 'nombre' => 'Toscana - Livorno'],
			['id_pais' => 29, 'nombre' => 'Toscana - Lucca'],
			['id_pais' => 29, 'nombre' => 'Toscana - Massa Carrara'],
			['id_pais' => 29, 'nombre' => 'Toscana - Pisa'],
			['id_pais' => 29, 'nombre' => 'Toscana - Pistoia'],
			['id_pais' => 29, 'nombre' => 'Toscana - Prato'],
			['id_pais' => 29, 'nombre' => 'Toscana - Siena'],
			['id_pais' => 29, 'nombre' => 'Umbria - Perugia'],
			['id_pais' => 29, 'nombre' => 'Umbria - Terni'],
			['id_pais' => 29, 'nombre' => 'Marche - Ancona'],
			['id_pais' => 29, 'nombre' => 'Marche - Ascoli Piceno'],
			['id_pais' => 29, 'nombre' => 'Marche - Macerata'],
			['id_pais' => 29, 'nombre' => 'Marche - Pesaro - Urbino'],
			['id_pais' => 29, 'nombre' => 'Lazio - Roma'],
			['id_pais' => 29, 'nombre' => 'Lazio - Frosinone'],
			['id_pais' => 29, 'nombre' => 'Lazio - Latina'],
			['id_pais' => 29, 'nombre' => 'Lazio - Rieti'],
			['id_pais' => 29, 'nombre' => 'Lazio - Viterbo'],
			['id_pais' => 29, 'nombre' => 'Abruzzo - LAquila'],
			['id_pais' => 29, 'nombre' => 'Abruzzo - Chieti'],
			['id_pais' => 29, 'nombre' => 'Abruzzo - Pescara'],
			['id_pais' => 29, 'nombre' => 'Abruzzo - Teramo'],
			['id_pais' => 29, 'nombre' => 'Molise - Campobasso'],
			['id_pais' => 29, 'nombre' => 'Molise - Isernia'],
			['id_pais' => 29, 'nombre' => 'Campania - Napoli'],
			['id_pais' => 29, 'nombre' => 'Campania - Avellino'],
			['id_pais' => 29, 'nombre' => 'Campania - Benevento'],
			['id_pais' => 29, 'nombre' => 'Campania - Caserta'],
			['id_pais' => 29, 'nombre' => 'Campania - Salerno'],
			['id_pais' => 29, 'nombre' => 'Puglia - Bari'],
			['id_pais' => 29, 'nombre' => 'Puglia - Brindisi'],
			['id_pais' => 29, 'nombre' => 'Puglia - Foggia'],
			['id_pais' => 29, 'nombre' => 'Puglia - Lecce'],
			['id_pais' => 29, 'nombre' => 'Puglia - Taranto'],
			['id_pais' => 29, 'nombre' => 'Basilicata - Potenza'],
			['id_pais' => 29, 'nombre' => 'Basilicata - Matera'],
			['id_pais' => 29, 'nombre' => 'Calabria - Catanzaro'],
			['id_pais' => 29, 'nombre' => 'Calabria - Cosenza'],
			['id_pais' => 29, 'nombre' => 'Calabria - Crotone'],
			['id_pais' => 29, 'nombre' => 'Calabria - Reggio Calabria'],
			['id_pais' => 29, 'nombre' => 'Calabria - Vibo Valentia'],
			['id_pais' => 29, 'nombre' => 'Sicilia - Palermo'],
			['id_pais' => 29, 'nombre' => 'Sicilia - Agrigento'],
			['id_pais' => 29, 'nombre' => 'Sicilia - Caltanissetta'],
			['id_pais' => 29, 'nombre' => 'Sicilia - Catania'],
			['id_pais' => 29, 'nombre' => 'Sicilia - Enna'],
			['id_pais' => 29, 'nombre' => 'Sicilia - Messina'],
			['id_pais' => 29, 'nombre' => 'Sicilia - Ragusa'],
			['id_pais' => 29, 'nombre' => 'Sicilia - Siracusa'],
			['id_pais' => 29, 'nombre' => 'Sicilia - Trapani'],
			['id_pais' => 29, 'nombre' => 'Sardegna - Cagliari'],
			['id_pais' => 29, 'nombre' => 'Sardegna - Nuoro'],
			['id_pais' => 29, 'nombre' => 'Sardegna - Oristano'],
			['id_pais' => 29, 'nombre' => 'Sardegna - Sassari'],
			['id_pais' => 28, 'nombre' => 'Las Palmas'],
			['id_pais' => 28, 'nombre' => 'Soria'],
			['id_pais' => 28, 'nombre' => 'Palencia'],
			['id_pais' => 28, 'nombre' => 'Zamora'],
			['id_pais' => 28, 'nombre' => 'Cádiz'],
			['id_pais' => 28, 'nombre' => 'Navarra'],
			['id_pais' => 28, 'nombre' => 'Ourense'],
			['id_pais' => 28, 'nombre' => 'Segovia'],
			['id_pais' => 28, 'nombre' => 'Guipúzcoa'],
			['id_pais' => 28, 'nombre' => 'Ciudad Real'],
			['id_pais' => 28, 'nombre' => 'Vizcaya'],
			['id_pais' => 28, 'nombre' => 'Álava'],
			['id_pais' => 28, 'nombre' => 'A Coruña'],
			['id_pais' => 28, 'nombre' => 'Cantabria'],
			['id_pais' => 28, 'nombre' => 'Almería'],
			['id_pais' => 28, 'nombre' => 'Zaragoza'],
			['id_pais' => 28, 'nombre' => 'Santa Cruz de Tenerife'],
			['id_pais' => 28, 'nombre' => 'Cáceres'],
			['id_pais' => 28, 'nombre' => 'Guadalajara'],
			['id_pais' => 28, 'nombre' => 'Ávila'],
			['id_pais' => 28, 'nombre' => 'Toledo'],
			['id_pais' => 28, 'nombre' => 'Castellón'],
			['id_pais' => 28, 'nombre' => 'Tarragona'],
			['id_pais' => 28, 'nombre' => 'Lugo'],
			['id_pais' => 28, 'nombre' => 'La Rioja'],
			['id_pais' => 28, 'nombre' => 'Ceuta'],
			['id_pais' => 28, 'nombre' => 'Murcia'],
			['id_pais' => 28, 'nombre' => 'Salamanca'],
			['id_pais' => 28, 'nombre' => 'Valladolid'],
			['id_pais' => 28, 'nombre' => 'Jaén'],
			['id_pais' => 28, 'nombre' => 'Girona'],
			['id_pais' => 28, 'nombre' => 'Granada'],
			['id_pais' => 28, 'nombre' => 'Alacant'],
			['id_pais' => 28, 'nombre' => 'Córdoba'],
			['id_pais' => 28, 'nombre' => 'Albacete'],
			['id_pais' => 28, 'nombre' => 'Cuenca'],
			['id_pais' => 28, 'nombre' => 'Pontevedra'],
			['id_pais' => 28, 'nombre' => 'Teruel'],
			['id_pais' => 28, 'nombre' => 'Melilla'],
			['id_pais' => 28, 'nombre' => 'Barcelona'],
			['id_pais' => 28, 'nombre' => 'Badajoz'],
			['id_pais' => 28, 'nombre' => 'Madrid'],
			['id_pais' => 28, 'nombre' => 'Sevilla'],
			['id_pais' => 28, 'nombre' => 'València'],
			['id_pais' => 28, 'nombre' => 'Huelva'],
			['id_pais' => 28, 'nombre' => 'Lleida'],
			['id_pais' => 28, 'nombre' => 'León'],
			['id_pais' => 28, 'nombre' => 'Illes Balears'],
			['id_pais' => 28, 'nombre' => 'Burgos'],
			['id_pais' => 28, 'nombre' => 'Huesca'],
			['id_pais' => 28, 'nombre' => 'Asturias'],
			['id_pais' => 28, 'nombre' => 'Málaga'],
			['id_pais' => 144, 'nombre' => 'Afghanistan'],
			['id_pais' => 210, 'nombre' => 'Niger'],
			['id_pais' => 133, 'nombre' => 'Mali'],
			['id_pais' => 156, 'nombre' => 'Burkina Faso'],
			['id_pais' => 136, 'nombre' => 'Togo'],
			['id_pais' => 151, 'nombre' => 'Benin'],
			['id_pais' => 119, 'nombre' => 'Angola'],
			['id_pais' => 102, 'nombre' => 'Namibia'],
			['id_pais' => 100, 'nombre' => 'Botswana'],
			['id_pais' => 134, 'nombre' => 'Madagascar'],
			['id_pais' => 202, 'nombre' => 'Mauritius'],
			['id_pais' => 196, 'nombre' => 'Laos'],
			['id_pais' => 158, 'nombre' => 'Cambodia'],
			['id_pais' => 90, 'nombre' => 'Philippines'],
			['id_pais' => 88, 'nombre' => 'Papua New Guinea'],
			['id_pais' => 228, 'nombre' => 'Solomon Islands'],
			['id_pais' => 240, 'nombre' => 'Vanuatu'],
			['id_pais' => 176, 'nombre' => 'Fiji'],
			['id_pais' => 223, 'nombre' => 'Samoa'],
			['id_pais' => 206, 'nombre' => 'Nauru'],
			['id_pais' => 168, 'nombre' => 'Cote DIvoire'],
			['id_pais' => 198, 'nombre' => 'Liberia'],
			['id_pais' => 187, 'nombre' => 'Guinea'],
			['id_pais' => 189, 'nombre' => 'Guyana'],
			['id_pais' => 98, 'nombre' => 'Algeria'],
			['id_pais' => 147, 'nombre' => 'Antigua and Barbuda'],
			['id_pais' => 127, 'nombre' => 'Bahrain'],
			['id_pais' => 149, 'nombre' => 'Bangladesh'],
			['id_pais' => 128, 'nombre' => 'Barbados'],
			['id_pais' => 152, 'nombre' => 'Bhutan'],
			['id_pais' => 155, 'nombre' => 'Brunei'],
			['id_pais' => 157, 'nombre' => 'Burundi'],
			['id_pais' => 159, 'nombre' => 'Cape Verde'],
			['id_pais' => 130, 'nombre' => 'Chad'],
			['id_pais' => 164, 'nombre' => 'Comoros'],
			['id_pais' => 112, 'nombre' => 'Congo (Brazzaville)'],
			['id_pais' => 169, 'nombre' => 'Djibouti'],
			['id_pais' => 171, 'nombre' => 'East Timor'],
			['id_pais' => 173, 'nombre' => 'Eritrea'],
			['id_pais' => 121, 'nombre' => 'Ethiopia'],
			['id_pais' => 180, 'nombre' => 'Gabon'],
			['id_pais' => 181, 'nombre' => 'Gambia'],
			['id_pais' => 105, 'nombre' => 'Ghana'],
			['id_pais' => 197, 'nombre' => 'Lesotho'],
			['id_pais' => 125, 'nombre' => 'Malawi'],
			['id_pais' => 200, 'nombre' => 'Maldives'],
			['id_pais' => 205, 'nombre' => 'Myanmar (Burma)'],
			['id_pais' => 107, 'nombre' => 'Nepal'],
			['id_pais' => 213, 'nombre' => 'Oman'],
			['id_pais' => 217, 'nombre' => 'Rwanda'],
			['id_pais' => 91, 'nombre' => 'Saudi Arabia'],
			['id_pais' => 120, 'nombre' => 'Sri Lanka'],
			['id_pais' => 232, 'nombre' => 'Sudan'],
			['id_pais' => 234, 'nombre' => 'Swaziland'],
			['id_pais' => 101, 'nombre' => 'Tanzania'],
			['id_pais' => 236, 'nombre' => 'Tonga'],
			['id_pais' => 239, 'nombre' => 'Tuvalu'],
			['id_pais' => 242, 'nombre' => 'Western Sahara'],
			['id_pais' => 243, 'nombre' => 'Yemen'],
			['id_pais' => 116, 'nombre' => 'Zambia'],
			['id_pais' => 96, 'nombre' => 'Zimbabwe'],
			['id_pais' => 66, 'nombre' => 'Aargau'],
			['id_pais' => 66, 'nombre' => 'Appenzell Innerrhoden'],
			['id_pais' => 66, 'nombre' => 'Appenzell Ausserrhoden'],
			['id_pais' => 66, 'nombre' => 'Bern'],
			['id_pais' => 66, 'nombre' => 'Basel-Landschaft'],
			['id_pais' => 66, 'nombre' => 'Basel-Stadt'],
			['id_pais' => 66, 'nombre' => 'Fribourg'],
			['id_pais' => 66, 'nombre' => 'Genève'],
			['id_pais' => 66, 'nombre' => 'Glarus'],
			['id_pais' => 66, 'nombre' => 'Graubünden'],
			['id_pais' => 66, 'nombre' => 'Jura'],
			['id_pais' => 66, 'nombre' => 'Luzern'],
			['id_pais' => 66, 'nombre' => 'Neuchâtel'],
			['id_pais' => 66, 'nombre' => 'Nidwalden'],
			['id_pais' => 66, 'nombre' => 'Obwalden'],
			['id_pais' => 66, 'nombre' => 'Sankt Gallen'],
			['id_pais' => 66, 'nombre' => 'Schaffhausen'],
			['id_pais' => 66, 'nombre' => 'Solothurn'],
			['id_pais' => 66, 'nombre' => 'Schwyz'],
			['id_pais' => 66, 'nombre' => 'Thurgau'],
			['id_pais' => 66, 'nombre' => 'Ticino'],
			['id_pais' => 66, 'nombre' => 'Uri'],
			['id_pais' => 66, 'nombre' => 'Vaud'],
			['id_pais' => 66, 'nombre' => 'Valais'],
			['id_pais' => 66, 'nombre' => 'Zug'],
			['id_pais' => 66, 'nombre' => 'Zürich'],
			['id_pais' => 48, 'nombre' => 'Aveiro'],
			['id_pais' => 48, 'nombre' => 'Beja'],
			['id_pais' => 48, 'nombre' => 'Braga'],
			['id_pais' => 48, 'nombre' => 'Braganca'],
			['id_pais' => 48, 'nombre' => 'Castelo Branco'],
			['id_pais' => 48, 'nombre' => 'Coimbra'],
			['id_pais' => 48, 'nombre' => 'Evora'],
			['id_pais' => 48, 'nombre' => 'Faro'],
			['id_pais' => 48, 'nombre' => 'Madeira'],
			['id_pais' => 48, 'nombre' => 'Guarda'],
			['id_pais' => 48, 'nombre' => 'Leiria'],
			['id_pais' => 48, 'nombre' => 'Lisboa'],
			['id_pais' => 48, 'nombre' => 'Portalegre'],
			['id_pais' => 48, 'nombre' => 'Porto'],
			['id_pais' => 48, 'nombre' => 'Santarem'],
			['id_pais' => 48, 'nombre' => 'Setubal'],
			['id_pais' => 48, 'nombre' => 'Viana do Castelo'],
			['id_pais' => 48, 'nombre' => 'Vila Real'],
			['id_pais' => 48, 'nombre' => 'Viseu'],
			['id_pais' => 48, 'nombre' => 'Azores'],
			['id_pais' => 55, 'nombre' => 'Armed Forces Americas'],
			['id_pais' => 55, 'nombre' => 'Armed Forces Europe'],
			['id_pais' => 55, 'nombre' => 'Alaska'],
			['id_pais' => 55, 'nombre' => 'Alabama'],
			['id_pais' => 55, 'nombre' => 'Armed Forces Pacific'],
			['id_pais' => 55, 'nombre' => 'Arkansas'],
			['id_pais' => 55, 'nombre' => 'American Samoa'],
			['id_pais' => 55, 'nombre' => 'Arizona'],
			['id_pais' => 55, 'nombre' => 'California'],
			['id_pais' => 55, 'nombre' => 'Colorado'],
			['id_pais' => 55, 'nombre' => 'Connecticut'],
			['id_pais' => 55, 'nombre' => 'District of Columbia'],
			['id_pais' => 55, 'nombre' => 'Delaware'],
			['id_pais' => 55, 'nombre' => 'Florida'],
			['id_pais' => 55, 'nombre' => 'Federated Statess of Micronesia'],
			['id_pais' => 55, 'nombre' => 'Georgia'],
			['id_pais' => 55, 'nombre' => 'Hawaii'],
			['id_pais' => 55, 'nombre' => 'Iowa'],
			['id_pais' => 55, 'nombre' => 'Idaho'],
			['id_pais' => 55, 'nombre' => 'Illinois'],
			['id_pais' => 55, 'nombre' => 'Indiana'],
			['id_pais' => 55, 'nombre' => 'Kansas'],
			['id_pais' => 55, 'nombre' => 'Kentucky'],
			['id_pais' => 55, 'nombre' => 'Louisiana'],
			['id_pais' => 55, 'nombre' => 'Massachusetts'],
			['id_pais' => 55, 'nombre' => 'Maryland'],
			['id_pais' => 55, 'nombre' => 'Maine'],
			['id_pais' => 55, 'nombre' => 'Marshall Islands'],
			['id_pais' => 55, 'nombre' => 'Michigan'],
			['id_pais' => 55, 'nombre' => 'Minnesota'],
			['id_pais' => 55, 'nombre' => 'Missouri'],
			['id_pais' => 55, 'nombre' => 'Northern Mariana Islands'],
			['id_pais' => 55, 'nombre' => 'Mississippi'],
			['id_pais' => 55, 'nombre' => 'Montana'],
			['id_pais' => 55, 'nombre' => 'North Carolina'],
			['id_pais' => 55, 'nombre' => 'North Dakota'],
			['id_pais' => 55, 'nombre' => 'Nebraska'],
			['id_pais' => 55, 'nombre' => 'New Hampshire'],
			['id_pais' => 55, 'nombre' => 'New Jersey'],
			['id_pais' => 55, 'nombre' => 'New Mexico'],
			['id_pais' => 55, 'nombre' => 'Nevada'],
			['id_pais' => 55, 'nombre' => 'New York'],
			['id_pais' => 55, 'nombre' => 'Ohio'],
			['id_pais' => 55, 'nombre' => 'Oklahoma'],
			['id_pais' => 55, 'nombre' => 'Oregon'],
			['id_pais' => 55, 'nombre' => 'Pennsylvania'],
			['id_pais' => 246, 'nombre' => 'Puerto Rico'],
			['id_pais' => 55, 'nombre' => 'Palau'],
			['id_pais' => 55, 'nombre' => 'Rhode Island'],
			['id_pais' => 55, 'nombre' => 'South Carolina'],
			['id_pais' => 55, 'nombre' => 'South Dakota'],
			['id_pais' => 55, 'nombre' => 'Tennessee'],
			['id_pais' => 55, 'nombre' => 'Texas'],
			['id_pais' => 55, 'nombre' => 'Utah'],
			['id_pais' => 55, 'nombre' => 'Virginia'],
			['id_pais' => 55, 'nombre' => 'Virgin Islands'],
			['id_pais' => 55, 'nombre' => 'Vermont'],
			['id_pais' => 55, 'nombre' => 'Washington'],
			['id_pais' => 55, 'nombre' => 'West Virginia'],
			['id_pais' => 55, 'nombre' => 'Wisconsin'],
			['id_pais' => 55, 'nombre' => 'Wyoming'],
			['id_pais' => 94, 'nombre' => 'Greenland'],
			['id_pais' => 18, 'nombre' => 'Brandenburg'],
			['id_pais' => 18, 'nombre' => 'Baden-Württemberg'],
			['id_pais' => 18, 'nombre' => 'Bayern'],
			['id_pais' => 18, 'nombre' => 'Hessen'],
			['id_pais' => 18, 'nombre' => 'Hamburg'],
			['id_pais' => 18, 'nombre' => 'Mecklenburg-Vorpommern'],
			['id_pais' => 18, 'nombre' => 'Niedersachsen'],
			['id_pais' => 18, 'nombre' => 'Nordrhein-Westfalen'],
			['id_pais' => 18, 'nombre' => 'Rheinland-Pfalz'],
			['id_pais' => 18, 'nombre' => 'Schleswig-Holstein'],
			['id_pais' => 18, 'nombre' => 'Sachsen'],
			['id_pais' => 18, 'nombre' => 'Sachsen-Anhalt'],
			['id_pais' => 18, 'nombre' => 'Thüringen'],
			['id_pais' => 18, 'nombre' => 'Berlin'],
			['id_pais' => 18, 'nombre' => 'Bremen'],
			['id_pais' => 18, 'nombre' => 'Saarland'],
			['id_pais' => 13, 'nombre' => 'Scotland North'],
			['id_pais' => 13, 'nombre' => 'England - East'],
			['id_pais' => 13, 'nombre' => 'England - West Midlands'],
			['id_pais' => 13, 'nombre' => 'England - South West'],
			['id_pais' => 13, 'nombre' => 'England - North West'],
			['id_pais' => 13, 'nombre' => 'England - Yorks Y Humber'],
			['id_pais' => 13, 'nombre' => 'England - South East'],
			['id_pais' => 13, 'nombre' => 'England - London'],
			['id_pais' => 13, 'nombre' => 'Northern Ireland'],
			['id_pais' => 13, 'nombre' => 'England - North East'],
			['id_pais' => 13, 'nombre' => 'Wales South'],
			['id_pais' => 13, 'nombre' => 'Wales North'],
			['id_pais' => 13, 'nombre' => 'England - East Midlands'],
			['id_pais' => 13, 'nombre' => 'Scotland Central'],
			['id_pais' => 13, 'nombre' => 'Scotland South'],
			['id_pais' => 13, 'nombre' => 'Channel Islands'],
			['id_pais' => 13, 'nombre' => 'Isle of Man'],
			['id_pais' => 2, 'nombre' => 'Burgenland'],
			['id_pais' => 2, 'nombre' => 'Kärnten'],
			['id_pais' => 2, 'nombre' => 'Niederösterreich'],
			['id_pais' => 2, 'nombre' => 'Oberösterreich'],
			['id_pais' => 2, 'nombre' => 'Salzburg'],
			['id_pais' => 2, 'nombre' => 'Steiermark'],
			['id_pais' => 2, 'nombre' => 'Tirol'],
			['id_pais' => 2, 'nombre' => 'Vorarlberg'],
			['id_pais' => 2, 'nombre' => 'Wien'],
			['id_pais' => 9, 'nombre' => 'Bruxelles'],
			['id_pais' => 9, 'nombre' => 'West-Vlaanderen'],
			['id_pais' => 9, 'nombre' => 'Oost-Vlaanderen'],
			['id_pais' => 9, 'nombre' => 'Limburg'],
			['id_pais' => 9, 'nombre' => 'Vlaams Brabant'],
			['id_pais' => 9, 'nombre' => 'Antwerpen'],
			['id_pais' => 9, 'nombre' => 'LiÃ„Âge'],
			['id_pais' => 9, 'nombre' => 'Namur'],
			['id_pais' => 9, 'nombre' => 'Hainaut'],
			['id_pais' => 9, 'nombre' => 'Luxembourg'],
			['id_pais' => 9, 'nombre' => 'Brabant Wallon'],
			['id_pais' => 67, 'nombre' => 'Blekinge Lan'],
			['id_pais' => 67, 'nombre' => 'Gavleborgs Lan'],
			['id_pais' => 67, 'nombre' => 'Gotlands Lan'],
			['id_pais' => 67, 'nombre' => 'Hallands Lan'],
			['id_pais' => 67, 'nombre' => 'Jamtlands Lan'],
			['id_pais' => 67, 'nombre' => 'Jonkopings Lan'],
			['id_pais' => 67, 'nombre' => 'Kalmar Lan'],
			['id_pais' => 67, 'nombre' => 'Dalarnas Lan'],
			['id_pais' => 67, 'nombre' => 'Kronobergs Lan'],
			['id_pais' => 67, 'nombre' => 'Norrbottens Lan'],
			['id_pais' => 67, 'nombre' => 'Orebro Lan'],
			['id_pais' => 67, 'nombre' => 'Ostergotlands Lan'],
			['id_pais' => 67, 'nombre' => 'Sodermanlands Lan'],
			['id_pais' => 67, 'nombre' => 'Uppsala Lan'],
			['id_pais' => 67, 'nombre' => 'Varmlands Lan'],
			['id_pais' => 67, 'nombre' => 'Vasterbottens Lan'],
			['id_pais' => 67, 'nombre' => 'Vasternorrlands Lan'],
			['id_pais' => 67, 'nombre' => 'Vastmanlands Lan'],
			['id_pais' => 67, 'nombre' => 'Stockholms Lan'],
			['id_pais' => 67, 'nombre' => 'Skane Lan'],
			['id_pais' => 67, 'nombre' => 'Vastra Gotaland'],
			['id_pais' => 46, 'nombre' => 'Akershus'],
			['id_pais' => 46, 'nombre' => 'Aust-Agder'],
			['id_pais' => 46, 'nombre' => 'Buskerud'],
			['id_pais' => 46, 'nombre' => 'Finnmark'],
			['id_pais' => 46, 'nombre' => 'Hedmark'],
			['id_pais' => 46, 'nombre' => 'Hordaland'],
			['id_pais' => 46, 'nombre' => 'More og Romsdal'],
			['id_pais' => 46, 'nombre' => 'Nordland'],
			['id_pais' => 46, 'nombre' => 'Nord-Trondelag'],
			['id_pais' => 46, 'nombre' => 'Oppland'],
			['id_pais' => 46, 'nombre' => 'Oslo'],
			['id_pais' => 46, 'nombre' => 'Ostfold'],
			['id_pais' => 46, 'nombre' => 'Rogaland'],
			['id_pais' => 46, 'nombre' => 'Sogn og Fjordane'],
			['id_pais' => 46, 'nombre' => 'Sor-Trondelag'],
			['id_pais' => 46, 'nombre' => 'Telemark'],
			['id_pais' => 46, 'nombre' => 'Troms'],
			['id_pais' => 46, 'nombre' => 'Vest-Agder'],
			['id_pais' => 46, 'nombre' => 'Vestfold'],
			['id_pais' => 63, 'nombre' => 'Ð•land'],
			['id_pais' => 63, 'nombre' => 'Lapland'],
			['id_pais' => 63, 'nombre' => 'Oulu'],
			['id_pais' => 63, 'nombre' => 'Southern Finland'],
			['id_pais' => 63, 'nombre' => 'Eastern Finland'],
			['id_pais' => 63, 'nombre' => 'Western Finland'],
			['id_pais' => 22, 'nombre' => 'Arhus'],
			['id_pais' => 22, 'nombre' => 'Bornholm'],
			['id_pais' => 22, 'nombre' => 'Frederiksborg'],
			['id_pais' => 22, 'nombre' => 'Fyn'],
			['id_pais' => 22, 'nombre' => 'Kobenhavn'],
			['id_pais' => 22, 'nombre' => 'Staden Kobenhavn'],
			['id_pais' => 22, 'nombre' => 'Nordjylland'],
			['id_pais' => 22, 'nombre' => 'Ribe'],
			['id_pais' => 22, 'nombre' => 'Ringkobing'],
			['id_pais' => 22, 'nombre' => 'Roskilde'],
			['id_pais' => 22, 'nombre' => 'Sonderjylland'],
			['id_pais' => 22, 'nombre' => 'Storstrom'],
			['id_pais' => 22, 'nombre' => 'Vejle'],
			['id_pais' => 22, 'nombre' => 'Vestsjalland'],
			['id_pais' => 22, 'nombre' => 'Viborg'],
			['id_pais' => 65, 'nombre' => 'Hlavni Mesto Praha'],
			['id_pais' => 65, 'nombre' => 'Jihomoravsky Kraj'],
			['id_pais' => 65, 'nombre' => 'Jihocesky Kraj'],
			['id_pais' => 65, 'nombre' => 'Vysocina'],
			['id_pais' => 65, 'nombre' => 'Karlovarsky Kraj'],
			['id_pais' => 65, 'nombre' => 'Kralovehradecky Kraj'],
			['id_pais' => 65, 'nombre' => 'Liberecky Kraj'],
			['id_pais' => 65, 'nombre' => 'Olomoucky Kraj'],
			['id_pais' => 65, 'nombre' => 'Moravskoslezsky Kraj'],
			['id_pais' => 65, 'nombre' => 'Pardubicky Kraj'],
			['id_pais' => 65, 'nombre' => 'Plzensky Kraj'],
			['id_pais' => 65, 'nombre' => 'Stredocesky Kraj'],
			['id_pais' => 65, 'nombre' => 'Ustecky Kraj'],
			['id_pais' => 65, 'nombre' => 'Zlinsky Kraj'],
			['id_pais' => 114, 'nombre' => 'Berat'],
			['id_pais' => 114, 'nombre' => 'Diber'],
			['id_pais' => 114, 'nombre' => 'Durres'],
			['id_pais' => 114, 'nombre' => 'Elbasan'],
			['id_pais' => 114, 'nombre' => 'Fier'],
			['id_pais' => 114, 'nombre' => 'Gjirokaster'],
			['id_pais' => 114, 'nombre' => 'Korce'],
			['id_pais' => 114, 'nombre' => 'Kukes'],
			['id_pais' => 114, 'nombre' => 'Lezhe'],
			['id_pais' => 114, 'nombre' => 'Shkoder'],
			['id_pais' => 114, 'nombre' => 'Tirane'],
			['id_pais' => 114, 'nombre' => 'Vlore'],
			['id_pais' => 145, 'nombre' => 'Canillo'],
			['id_pais' => 145, 'nombre' => 'Encamp'],
			['id_pais' => 145, 'nombre' => 'La Massana'],
			['id_pais' => 145, 'nombre' => 'Ordino'],
			['id_pais' => 145, 'nombre' => 'Sant Julia de Loria'],
			['id_pais' => 145, 'nombre' => 'Andorra la Vella'],
			['id_pais' => 145, 'nombre' => 'Escaldes-Engordany'],
			['id_pais' => 6, 'nombre' => 'Aragatsotn'],
			['id_pais' => 6, 'nombre' => 'Ararat'],
			['id_pais' => 6, 'nombre' => 'Armavir'],
			['id_pais' => 6, 'nombre' => 'Gegharkunik'],
			['id_pais' => 6, 'nombre' => 'Kotayk'],
			['id_pais' => 6, 'nombre' => 'Lorri'],
			['id_pais' => 6, 'nombre' => 'Shirak'],
			['id_pais' => 6, 'nombre' => 'Syunik'],
			['id_pais' => 6, 'nombre' => 'Tavush'],
			['id_pais' => 6, 'nombre' => 'Vayots Dzor'],
			['id_pais' => 6, 'nombre' => 'Yerevan'],
			['id_pais' => 79, 'nombre' => 'Federation of Bosnia and Herzegovina'],
			['id_pais' => 79, 'nombre' => 'Republika Srpska'],
			['id_pais' => 11, 'nombre' => 'Mikhaylovgrad'],
			['id_pais' => 11, 'nombre' => 'Blagoevgrad'],
			['id_pais' => 11, 'nombre' => 'Burgas'],
			['id_pais' => 11, 'nombre' => 'Dobrich'],
			['id_pais' => 11, 'nombre' => 'Gabrovo'],
			['id_pais' => 11, 'nombre' => 'Grad Sofiya'],
			['id_pais' => 11, 'nombre' => 'Khaskovo'],
			['id_pais' => 11, 'nombre' => 'Kurdzhali'],
			['id_pais' => 11, 'nombre' => 'Kyustendil'],
			['id_pais' => 11, 'nombre' => 'Lovech'],
			['id_pais' => 11, 'nombre' => 'Montana'],
			['id_pais' => 11, 'nombre' => 'Pazardzhik'],
			['id_pais' => 11, 'nombre' => 'Pernik'],
			['id_pais' => 11, 'nombre' => 'Pleven'],
			['id_pais' => 11, 'nombre' => 'Plovdiv'],
			['id_pais' => 11, 'nombre' => 'Razgrad'],
			['id_pais' => 11, 'nombre' => 'Ruse'],
			['id_pais' => 11, 'nombre' => 'Shumen'],
			['id_pais' => 11, 'nombre' => 'Silistra'],
			['id_pais' => 11, 'nombre' => 'Sliven'],
			['id_pais' => 11, 'nombre' => 'Smolyan'],
			['id_pais' => 11, 'nombre' => 'Sofiya'],
			['id_pais' => 11, 'nombre' => 'Stara Zagora'],
			['id_pais' => 11, 'nombre' => 'Turgovishte'],
			['id_pais' => 11, 'nombre' => 'Varna'],
			['id_pais' => 11, 'nombre' => 'Veliko Turnovo'],
			['id_pais' => 11, 'nombre' => 'Vidin'],
			['id_pais' => 11, 'nombre' => 'Vratsa'],
			['id_pais' => 11, 'nombre' => 'Yambol'],
			['id_pais' => 71, 'nombre' => 'Bjelovarsko-Bilogorska'],
			['id_pais' => 71, 'nombre' => 'Brodsko-Posavska'],
			['id_pais' => 71, 'nombre' => 'Dubrovacko-Neretvanska'],
			['id_pais' => 71, 'nombre' => 'Istarska'],
			['id_pais' => 71, 'nombre' => 'Karlovacka'],
			['id_pais' => 71, 'nombre' => 'Koprivnicko-Krizevacka'],
			['id_pais' => 71, 'nombre' => 'Krapinsko-Zagorska'],
			['id_pais' => 71, 'nombre' => 'Licko-Senjska'],
			['id_pais' => 71, 'nombre' => 'Medimurska'],
			['id_pais' => 71, 'nombre' => 'Osjecko-Baranjska'],
			['id_pais' => 71, 'nombre' => 'Pozesko-Slavonska'],
			['id_pais' => 71, 'nombre' => 'Primorsko-Goranska'],
			['id_pais' => 71, 'nombre' => 'Sibensko-Kninska'],
			['id_pais' => 71, 'nombre' => 'Sisacko-Moslavacka'],
			['id_pais' => 71, 'nombre' => 'Splitsko-Dalmatinska'],
			['id_pais' => 71, 'nombre' => 'Varazdinska'],
			['id_pais' => 71, 'nombre' => 'Viroviticko-Podravska'],
			['id_pais' => 71, 'nombre' => 'Vukovarsko-Srijemska'],
			['id_pais' => 71, 'nombre' => 'Zadarska'],
			['id_pais' => 71, 'nombre' => 'Zagrebacka'],
			['id_pais' => 71, 'nombre' => 'Grad Zagreb'],
			['id_pais' => 143, 'nombre' => 'Gibraltar'],
			['id_pais' => 20, 'nombre' => 'Evros'],
			['id_pais' => 20, 'nombre' => 'Rodhopi'],
			['id_pais' => 20, 'nombre' => 'Xanthi'],
			['id_pais' => 20, 'nombre' => 'Drama'],
			['id_pais' => 20, 'nombre' => 'Serrai'],
			['id_pais' => 20, 'nombre' => 'Kilkis'],
			['id_pais' => 20, 'nombre' => 'Pella'],
			['id_pais' => 20, 'nombre' => 'Florina'],
			['id_pais' => 20, 'nombre' => 'Kastoria'],
			['id_pais' => 20, 'nombre' => 'Grevena'],
			['id_pais' => 20, 'nombre' => 'Kozani'],
			['id_pais' => 20, 'nombre' => 'Imathia'],
			['id_pais' => 20, 'nombre' => 'Thessaloniki'],
			['id_pais' => 20, 'nombre' => 'Kavala'],
			['id_pais' => 20, 'nombre' => 'Khalkidhiki'],
			['id_pais' => 20, 'nombre' => 'Pieria'],
			['id_pais' => 20, 'nombre' => 'Ioannina'],
			['id_pais' => 20, 'nombre' => 'Thesprotia'],
			['id_pais' => 20, 'nombre' => 'Preveza'],
			['id_pais' => 20, 'nombre' => 'Arta'],
			['id_pais' => 20, 'nombre' => 'Larisa'],
			['id_pais' => 20, 'nombre' => 'Trikala'],
			['id_pais' => 20, 'nombre' => 'Kardhitsa'],
			['id_pais' => 20, 'nombre' => 'Magnisia'],
			['id_pais' => 20, 'nombre' => 'Kerkira'],
			['id_pais' => 20, 'nombre' => 'Levkas'],
			['id_pais' => 20, 'nombre' => 'Kefallinia'],
			['id_pais' => 20, 'nombre' => 'Zakinthos'],
			['id_pais' => 20, 'nombre' => 'Fthiotis'],
			['id_pais' => 20, 'nombre' => 'Evritania'],
			['id_pais' => 20, 'nombre' => 'Aitolia kai Akarnania'],
			['id_pais' => 20, 'nombre' => 'Fokis'],
			['id_pais' => 20, 'nombre' => 'Voiotia'],
			['id_pais' => 20, 'nombre' => 'Evvoia'],
			['id_pais' => 20, 'nombre' => 'Attiki'],
			['id_pais' => 20, 'nombre' => 'Argolis'],
			['id_pais' => 20, 'nombre' => 'Korinthia'],
			['id_pais' => 20, 'nombre' => 'Akhaia'],
			['id_pais' => 20, 'nombre' => 'Ilia'],
			['id_pais' => 20, 'nombre' => 'Messinia'],
			['id_pais' => 20, 'nombre' => 'Arkadhia'],
			['id_pais' => 20, 'nombre' => 'Lakonia'],
			['id_pais' => 20, 'nombre' => 'Khania'],
			['id_pais' => 20, 'nombre' => 'Rethimni'],
			['id_pais' => 20, 'nombre' => 'Iraklion'],
			['id_pais' => 20, 'nombre' => 'Lasithi'],
			['id_pais' => 20, 'nombre' => 'Dhodhekanisos'],
			['id_pais' => 20, 'nombre' => 'Samos'],
			['id_pais' => 20, 'nombre' => 'Kikladhes'],
			['id_pais' => 20, 'nombre' => 'Khios'],
			['id_pais' => 20, 'nombre' => 'Lesvos'],
			['id_pais' => 14, 'nombre' => 'Bacs-Kiskun'],
			['id_pais' => 14, 'nombre' => 'Baranya'],
			['id_pais' => 14, 'nombre' => 'Bekes'],
			['id_pais' => 14, 'nombre' => 'Borsod-Abauj-Zemplen'],
			['id_pais' => 14, 'nombre' => 'Budapest'],
			['id_pais' => 14, 'nombre' => 'Csongrad'],
			['id_pais' => 14, 'nombre' => 'Debrecen'],
			['id_pais' => 14, 'nombre' => 'Fejer'],
			['id_pais' => 14, 'nombre' => 'Gyor-Moson-Sopron'],
			['id_pais' => 14, 'nombre' => 'Hajdu-Bihar'],
			['id_pais' => 14, 'nombre' => 'Heves'],
			['id_pais' => 14, 'nombre' => 'Komarom-Esztergom'],
			['id_pais' => 14, 'nombre' => 'Miskolc'],
			['id_pais' => 14, 'nombre' => 'Nograd'],
			['id_pais' => 14, 'nombre' => 'Pecs'],
			['id_pais' => 14, 'nombre' => 'Pest'],
			['id_pais' => 14, 'nombre' => 'Somogy'],
			['id_pais' => 14, 'nombre' => 'Szabolcs-Szatmar-Bereg'],
			['id_pais' => 14, 'nombre' => 'Szeged'],
			['id_pais' => 14, 'nombre' => 'Jasz-Nagykun-Szolnok'],
			['id_pais' => 14, 'nombre' => 'Tolna'],
			['id_pais' => 14, 'nombre' => 'Vas'],
			['id_pais' => 14, 'nombre' => 'Veszprem'],
			['id_pais' => 14, 'nombre' => 'Zala'],
			['id_pais' => 14, 'nombre' => 'Gyor'],
			['id_pais' => 14, 'nombre' => 'Veszprem'],
			['id_pais' => 126, 'nombre' => 'Balzers'],
			['id_pais' => 126, 'nombre' => 'Eschen'],
			['id_pais' => 126, 'nombre' => 'Gamprin'],
			['id_pais' => 126, 'nombre' => 'Mauren'],
			['id_pais' => 126, 'nombre' => 'Planken'],
			['id_pais' => 126, 'nombre' => 'Ruggell'],
			['id_pais' => 126, 'nombre' => 'Schaan'],
			['id_pais' => 126, 'nombre' => 'Schellenberg'],
			['id_pais' => 126, 'nombre' => 'Triesen'],
			['id_pais' => 126, 'nombre' => 'Triesenberg'],
			['id_pais' => 126, 'nombre' => 'Vaduz'],
			['id_pais' => 41, 'nombre' => 'Diekirch'],
			['id_pais' => 41, 'nombre' => 'Grevenmacher'],
			['id_pais' => 41, 'nombre' => 'Luxembourg'],
			['id_pais' => 85, 'nombre' => 'Aracinovo'],
			['id_pais' => 85, 'nombre' => 'Bac'],
			['id_pais' => 85, 'nombre' => 'Belcista'],
			['id_pais' => 85, 'nombre' => 'Berovo'],
			['id_pais' => 85, 'nombre' => 'Bistrica'],
			['id_pais' => 85, 'nombre' => 'Bitola'],
			['id_pais' => 85, 'nombre' => 'Blatec'],
			['id_pais' => 85, 'nombre' => 'Bogdanci'],
			['id_pais' => 85, 'nombre' => 'Bogomila'],
			['id_pais' => 85, 'nombre' => 'Bogovinje'],
			['id_pais' => 85, 'nombre' => 'Bosilovo'],
			['id_pais' => 85, 'nombre' => 'Cair'],
			['id_pais' => 85, 'nombre' => 'Capari'],
			['id_pais' => 85, 'nombre' => 'Caska'],
			['id_pais' => 85, 'nombre' => 'Cegrane'],
			['id_pais' => 85, 'nombre' => 'Centar Zupa'],
			['id_pais' => 85, 'nombre' => 'Debar'],
			['id_pais' => 85, 'nombre' => 'Delcevo'],
			['id_pais' => 85, 'nombre' => 'Demir Hisar'],
			['id_pais' => 85, 'nombre' => 'Demir Kapija'],
			['id_pais' => 85, 'nombre' => 'Dorce Petrov'],
			['id_pais' => 85, 'nombre' => 'Gazi Baba'],
			['id_pais' => 85, 'nombre' => 'Gevgelija'],
			['id_pais' => 85, 'nombre' => 'Gostivar'],
			['id_pais' => 85, 'nombre' => 'Gradsko'],
			['id_pais' => 85, 'nombre' => 'Jegunovce'],
			['id_pais' => 85, 'nombre' => 'Kamenjane'],
			['id_pais' => 85, 'nombre' => 'Karpos'],
			['id_pais' => 85, 'nombre' => 'Kavadarci'],
			['id_pais' => 85, 'nombre' => 'Kicevo'],
			['id_pais' => 85, 'nombre' => 'Kisela Voda'],
			['id_pais' => 85, 'nombre' => 'Klecevce'],
			['id_pais' => 85, 'nombre' => 'Kocani'],
			['id_pais' => 85, 'nombre' => 'Kondovo'],
			['id_pais' => 85, 'nombre' => 'Kratovo'],
			['id_pais' => 85, 'nombre' => 'Krivogastani'],
			['id_pais' => 85, 'nombre' => 'Krusevo'],
			['id_pais' => 85, 'nombre' => 'Kumanovo'],
			['id_pais' => 85, 'nombre' => 'Labunista'],
			['id_pais' => 85, 'nombre' => 'Lipkovo'],
			['id_pais' => 85, 'nombre' => 'Makedonska Kamenica'],
			['id_pais' => 85, 'nombre' => 'Makedonski Brod'],
			['id_pais' => 85, 'nombre' => 'Murtino'],
			['id_pais' => 85, 'nombre' => 'Negotino'],
			['id_pais' => 85, 'nombre' => 'Novo Selo'],
			['id_pais' => 85, 'nombre' => 'Ohrid'],
			['id_pais' => 85, 'nombre' => 'Orizari'],
			['id_pais' => 85, 'nombre' => 'Petrovec'],
			['id_pais' => 85, 'nombre' => 'Prilep'],
			['id_pais' => 85, 'nombre' => 'Probistip'],
			['id_pais' => 85, 'nombre' => 'Radovis'],
			['id_pais' => 85, 'nombre' => 'Resen'],
			['id_pais' => 85, 'nombre' => 'Rosoman'],
			['id_pais' => 85, 'nombre' => 'Saraj'],
			['id_pais' => 85, 'nombre' => 'Srbinovo'],
			['id_pais' => 85, 'nombre' => 'Star Dojran'],
			['id_pais' => 85, 'nombre' => 'Stip'],
			['id_pais' => 85, 'nombre' => 'Struga'],
			['id_pais' => 85, 'nombre' => 'Strumica'],
			['id_pais' => 85, 'nombre' => 'Studenicani'],
			['id_pais' => 85, 'nombre' => 'Suto Orizari'],
			['id_pais' => 85, 'nombre' => 'Sveti Nikole'],
			['id_pais' => 85, 'nombre' => 'Tearce'],
			['id_pais' => 85, 'nombre' => 'Tetovo'],
			['id_pais' => 85, 'nombre' => 'Valandovo'],
			['id_pais' => 85, 'nombre' => 'Veles'],
			['id_pais' => 85, 'nombre' => 'Vevcani'],
			['id_pais' => 85, 'nombre' => 'Vinica'],
			['id_pais' => 85, 'nombre' => 'Vrapciste'],
			['id_pais' => 85, 'nombre' => 'Zelino'],
			['id_pais' => 85, 'nombre' => 'Zrnovci'],
			['id_pais' => 86, 'nombre' => 'Malta'],
			['id_pais' => 44, 'nombre' => 'La Condamine'],
			['id_pais' => 44, 'nombre' => 'Monaco'],
			['id_pais' => 44, 'nombre' => 'Monte-Carlo'],
			['id_pais' => 47, 'nombre' => 'Biala Podlaska'],
			['id_pais' => 47, 'nombre' => 'Bialystok'],
			['id_pais' => 47, 'nombre' => 'Bielsko'],
			['id_pais' => 47, 'nombre' => 'Bydgoszcz'],
			['id_pais' => 47, 'nombre' => 'Chelm'],
			['id_pais' => 47, 'nombre' => 'Ciechanow'],
			['id_pais' => 47, 'nombre' => 'Czestochowa'],
			['id_pais' => 47, 'nombre' => 'Elblag'],
			['id_pais' => 47, 'nombre' => 'Gdansk'],
			['id_pais' => 47, 'nombre' => 'Gorzow'],
			['id_pais' => 47, 'nombre' => 'Jelenia Gora'],
			['id_pais' => 47, 'nombre' => 'Kalisz'],
			['id_pais' => 47, 'nombre' => 'Katowice'],
			['id_pais' => 47, 'nombre' => 'Kielce'],
			['id_pais' => 47, 'nombre' => 'Konin'],
			['id_pais' => 47, 'nombre' => 'Koszalin'],
			['id_pais' => 47, 'nombre' => 'Krakow'],
			['id_pais' => 47, 'nombre' => 'Krosno'],
			['id_pais' => 47, 'nombre' => 'Legnica'],
			['id_pais' => 47, 'nombre' => 'Leszno'],
			['id_pais' => 47, 'nombre' => 'Lodz'],
			['id_pais' => 47, 'nombre' => 'Lomza'],
			['id_pais' => 47, 'nombre' => 'Lublin'],
			['id_pais' => 47, 'nombre' => 'Nowy Sacz'],
			['id_pais' => 47, 'nombre' => 'Olsztyn'],
			['id_pais' => 47, 'nombre' => 'Opole'],
			['id_pais' => 47, 'nombre' => 'Ostroleka'],
			['id_pais' => 47, 'nombre' => 'Pila'],
			['id_pais' => 47, 'nombre' => 'Piotrkow'],
			['id_pais' => 47, 'nombre' => 'Plock'],
			['id_pais' => 47, 'nombre' => 'Poznan'],
			['id_pais' => 47, 'nombre' => 'Przemysl'],
			['id_pais' => 47, 'nombre' => 'Radom'],
			['id_pais' => 47, 'nombre' => 'Rzeszow'],
			['id_pais' => 47, 'nombre' => 'Siedlce'],
			['id_pais' => 47, 'nombre' => 'Sieradz'],
			['id_pais' => 47, 'nombre' => 'Skierniewice'],
			['id_pais' => 47, 'nombre' => 'Slupsk'],
			['id_pais' => 47, 'nombre' => 'Suwalki'],
			['id_pais' => 47, 'nombre' => 'Tarnobrzeg'],
			['id_pais' => 47, 'nombre' => 'Tarnow'],
			['id_pais' => 47, 'nombre' => 'Torun'],
			['id_pais' => 47, 'nombre' => 'Walbrzych'],
			['id_pais' => 47, 'nombre' => 'Warszawa'],
			['id_pais' => 47, 'nombre' => 'Wloclawek'],
			['id_pais' => 47, 'nombre' => 'Wroclaw'],
			['id_pais' => 47, 'nombre' => 'Zamosc'],
			['id_pais' => 47, 'nombre' => 'Zielona Gora'],
			['id_pais' => 47, 'nombre' => 'Dolnoslaskie'],
			['id_pais' => 47, 'nombre' => 'Kujawsko-Pomorskie'],
			['id_pais' => 47, 'nombre' => 'Lodzkie'],
			['id_pais' => 47, 'nombre' => 'Lubelskie'],
			['id_pais' => 47, 'nombre' => 'Lubuskie'],
			['id_pais' => 47, 'nombre' => 'Malopolskie'],
			['id_pais' => 47, 'nombre' => 'Mazowieckie'],
			['id_pais' => 47, 'nombre' => 'Opolskie'],
			['id_pais' => 47, 'nombre' => 'Podkarpackie'],
			['id_pais' => 47, 'nombre' => 'Podlaskie'],
			['id_pais' => 47, 'nombre' => 'Pomorskie'],
			['id_pais' => 47, 'nombre' => 'Slaskie'],
			['id_pais' => 47, 'nombre' => 'Swietokrzyskie'],
			['id_pais' => 47, 'nombre' => 'Warminsko-Mazurskie'],
			['id_pais' => 47, 'nombre' => 'Wielkopolskie'],
			['id_pais' => 47, 'nombre' => 'Zachodniopomorskie'],
			['id_pais' => 72, 'nombre' => 'Alba'],
			['id_pais' => 72, 'nombre' => 'Arad'],
			['id_pais' => 72, 'nombre' => 'Arges'],
			['id_pais' => 72, 'nombre' => 'Bacau'],
			['id_pais' => 72, 'nombre' => 'Bihor'],
			['id_pais' => 72, 'nombre' => 'Bistrita-Nasaud'],
			['id_pais' => 72, 'nombre' => 'Botosani'],
			['id_pais' => 72, 'nombre' => 'Braila'],
			['id_pais' => 72, 'nombre' => 'Brasov'],
			['id_pais' => 72, 'nombre' => 'Bucuresti'],
			['id_pais' => 72, 'nombre' => 'Buzau'],
			['id_pais' => 72, 'nombre' => 'Caras-Severin'],
			['id_pais' => 72, 'nombre' => 'Cluj'],
			['id_pais' => 72, 'nombre' => 'Constanta'],
			['id_pais' => 72, 'nombre' => 'Covasna'],
			['id_pais' => 72, 'nombre' => 'Dambovita'],
			['id_pais' => 72, 'nombre' => 'Dolj'],
			['id_pais' => 72, 'nombre' => 'Galati'],
			['id_pais' => 72, 'nombre' => 'Gorj'],
			['id_pais' => 72, 'nombre' => 'Harghita'],
			['id_pais' => 72, 'nombre' => 'Hunedoara'],
			['id_pais' => 72, 'nombre' => 'Ialomita'],
			['id_pais' => 72, 'nombre' => 'Iasi'],
			['id_pais' => 72, 'nombre' => 'Maramures'],
			['id_pais' => 72, 'nombre' => 'Mehedinti'],
			['id_pais' => 72, 'nombre' => 'Mures'],
			['id_pais' => 72, 'nombre' => 'Neamt'],
			['id_pais' => 72, 'nombre' => 'Olt'],
			['id_pais' => 72, 'nombre' => 'Prahova'],
			['id_pais' => 72, 'nombre' => 'Salaj'],
			['id_pais' => 72, 'nombre' => 'Satu Mare'],
			['id_pais' => 72, 'nombre' => 'Sibiu'],
			['id_pais' => 72, 'nombre' => 'Suceava'],
			['id_pais' => 72, 'nombre' => 'Teleorman'],
			['id_pais' => 72, 'nombre' => 'Timis'],
			['id_pais' => 72, 'nombre' => 'Tulcea'],
			['id_pais' => 72, 'nombre' => 'Vaslui'],
			['id_pais' => 72, 'nombre' => 'Valcea'],
			['id_pais' => 72, 'nombre' => 'Vrancea'],
			['id_pais' => 72, 'nombre' => 'Calarasi'],
			['id_pais' => 72, 'nombre' => 'Giurgiu'],
			['id_pais' => 224, 'nombre' => 'Acquaviva'],
			['id_pais' => 224, 'nombre' => 'Chiesanuova'],
			['id_pais' => 224, 'nombre' => 'Domagnano'],
			['id_pais' => 224, 'nombre' => 'Faetano'],
			['id_pais' => 224, 'nombre' => 'Fiorentino'],
			['id_pais' => 224, 'nombre' => 'Borgo Maggiore'],
			['id_pais' => 224, 'nombre' => 'San Marino'],
			['id_pais' => 224, 'nombre' => 'Monte Giardino'],
			['id_pais' => 224, 'nombre' => 'Serravalle'],
			['id_pais' => 52, 'nombre' => 'Banska Bystrica'],
			['id_pais' => 52, 'nombre' => 'Bratislava'],
			['id_pais' => 52, 'nombre' => 'Kosice'],
			['id_pais' => 52, 'nombre' => 'Nitra'],
			['id_pais' => 52, 'nombre' => 'Presov'],
			['id_pais' => 52, 'nombre' => 'Trencin'],
			['id_pais' => 52, 'nombre' => 'Trnava'],
			['id_pais' => 52, 'nombre' => 'Zilina'],
			['id_pais' => 53, 'nombre' => 'Beltinci'],
			['id_pais' => 53, 'nombre' => 'Bohinj'],
			['id_pais' => 53, 'nombre' => 'Borovnica'],
			['id_pais' => 53, 'nombre' => 'Bovec'],
			['id_pais' => 53, 'nombre' => 'Brda'],
			['id_pais' => 53, 'nombre' => 'Brezice'],
			['id_pais' => 53, 'nombre' => 'Brezovica'],
			['id_pais' => 53, 'nombre' => 'Cerklje na Gorenjskem'],
			['id_pais' => 53, 'nombre' => 'Cerkno'],
			['id_pais' => 53, 'nombre' => 'Crna na Koroskem'],
			['id_pais' => 53, 'nombre' => 'Crnomelj'],
			['id_pais' => 53, 'nombre' => 'Divaca'],
			['id_pais' => 53, 'nombre' => 'Dobrepolje'],
			['id_pais' => 53, 'nombre' => 'Dol pri Ljubljani'],
			['id_pais' => 53, 'nombre' => 'Duplek'],
			['id_pais' => 53, 'nombre' => 'Gornji Grad'],
			['id_pais' => 53, 'nombre' => 'Hrastnik'],
			['id_pais' => 53, 'nombre' => 'Hrpelje-Kozina'],
			['id_pais' => 53, 'nombre' => 'Idrija'],
			['id_pais' => 53, 'nombre' => 'Ig'],
			['id_pais' => 53, 'nombre' => 'Ilirska Bistrica'],
			['id_pais' => 53, 'nombre' => 'Ivancna Gorica'],
			['id_pais' => 53, 'nombre' => 'Komen'],
			['id_pais' => 53, 'nombre' => 'Koper-Capodistria'],
			['id_pais' => 53, 'nombre' => 'Kozje'],
			['id_pais' => 53, 'nombre' => 'Kranj'],
			['id_pais' => 53, 'nombre' => 'Kranjska Gora'],
			['id_pais' => 53, 'nombre' => 'Krsko'],
			['id_pais' => 53, 'nombre' => 'Lasko'],
			['id_pais' => 53, 'nombre' => 'Ljubljana'],
			['id_pais' => 53, 'nombre' => 'Ljubno'],
			['id_pais' => 53, 'nombre' => 'Logatec'],
			['id_pais' => 53, 'nombre' => 'Medvode'],
			['id_pais' => 53, 'nombre' => 'Menges'],
			['id_pais' => 53, 'nombre' => 'Mezica'],
			['id_pais' => 53, 'nombre' => 'Moravce'],
			['id_pais' => 53, 'nombre' => 'Mozirje'],
			['id_pais' => 53, 'nombre' => 'Murska Sobota'],
			['id_pais' => 53, 'nombre' => 'Nova Gorica'],
			['id_pais' => 53, 'nombre' => 'Ormoz'],
			['id_pais' => 53, 'nombre' => 'Pesnica'],
			['id_pais' => 53, 'nombre' => 'Postojna'],
			['id_pais' => 53, 'nombre' => 'Radece'],
			['id_pais' => 53, 'nombre' => 'Radenci'],
			['id_pais' => 53, 'nombre' => 'Radovljica'],
			['id_pais' => 53, 'nombre' => 'Rogaska Slatina'],
			['id_pais' => 53, 'nombre' => 'Sencur'],
			['id_pais' => 53, 'nombre' => 'Sentilj'],
			['id_pais' => 53, 'nombre' => 'Sevnica'],
			['id_pais' => 53, 'nombre' => 'Sezana'],
			['id_pais' => 53, 'nombre' => 'Skofja Loka'],
			['id_pais' => 53, 'nombre' => 'Slovenj Gradec'],
			['id_pais' => 53, 'nombre' => 'Slovenske Konjice'],
			['id_pais' => 53, 'nombre' => 'Smarje pri Jelsah'],
			['id_pais' => 53, 'nombre' => 'Tolmin'],
			['id_pais' => 53, 'nombre' => 'Trbovlje'],
			['id_pais' => 53, 'nombre' => 'Trzic'],
			['id_pais' => 53, 'nombre' => 'Velenje'],
			['id_pais' => 53, 'nombre' => 'Vipava'],
			['id_pais' => 53, 'nombre' => 'Vrhnika'],
			['id_pais' => 53, 'nombre' => 'Vuzenica'],
			['id_pais' => 53, 'nombre' => 'Zagorje ob Savi'],
			['id_pais' => 53, 'nombre' => 'Zelezniki'],
			['id_pais' => 53, 'nombre' => 'Ziri'],
			['id_pais' => 53, 'nombre' => 'Zrece'],
			['id_pais' => 53, 'nombre' => 'Domzale'],
			['id_pais' => 53, 'nombre' => 'Jesenice'],
			['id_pais' => 53, 'nombre' => 'Kamnik'],
			['id_pais' => 53, 'nombre' => 'Kocevje'],
			['id_pais' => 53, 'nombre' => 'Lenart'],
			['id_pais' => 53, 'nombre' => 'Litija'],
			['id_pais' => 53, 'nombre' => 'Ljutomer'],
			['id_pais' => 53, 'nombre' => 'Maribor'],
			['id_pais' => 53, 'nombre' => 'Novo Mesto'],
			['id_pais' => 53, 'nombre' => 'Piran'],
			['id_pais' => 53, 'nombre' => 'Preddvor'],
			['id_pais' => 53, 'nombre' => 'Ptuj'],
			['id_pais' => 53, 'nombre' => 'Ribnica'],
			['id_pais' => 53, 'nombre' => 'Sentjur pri Celju'],
			['id_pais' => 53, 'nombre' => 'Slovenska Bistrica'],
			['id_pais' => 53, 'nombre' => 'Videm'],
			['id_pais' => 53, 'nombre' => 'Zalec'],
			['id_pais' => 109, 'nombre' => 'Seychelles'],
			['id_pais' => 108, 'nombre' => 'Mauritania'],
			['id_pais' => 135, 'nombre' => 'Senegal'],
			['id_pais' => 154, 'nombre' => 'Road Town'],
			['id_pais' => 165, 'nombre' => 'Congo'],
			['id_pais' => 166, 'nombre' => 'Avarua'],
			['id_pais' => 172, 'nombre' => 'Malabo'],
			['id_pais' => 175, 'nombre' => 'Torshavn'],
			['id_pais' => 178, 'nombre' => 'Papeete'],
			['id_pais' => 184, 'nombre' => 'St Georges'],
			['id_pais' => 186, 'nombre' => 'St Peter Port'],
			['id_pais' => 188, 'nombre' => 'Bissau'],
			['id_pais' => 193, 'nombre' => 'Saint Helier'],
			['id_pais' => 201, 'nombre' => 'Fort-de-France'],
			['id_pais' => 207, 'nombre' => 'Willemstad'],
			['id_pais' => 208, 'nombre' => 'Noumea'],
			['id_pais' => 212, 'nombre' => 'Kingston'],
			['id_pais' => 215, 'nombre' => 'Adamstown'],
			['id_pais' => 216, 'nombre' => 'Doha'],
			['id_pais' => 218, 'nombre' => 'Jamestown'],
			['id_pais' => 219, 'nombre' => 'Basseterre'],
			['id_pais' => 220, 'nombre' => 'Castries'],
			['id_pais' => 221, 'nombre' => 'Saint Pierre'],
			['id_pais' => 222, 'nombre' => 'Kingstown'],
			['id_pais' => 225, 'nombre' => 'San Tome'],
			['id_pais' => 226, 'nombre' => 'Belgrade'],
			['id_pais' => 227, 'nombre' => 'Freetown'],
			['id_pais' => 229, 'nombre' => 'Mogadishu'],
			['id_pais' => 235, 'nombre' => 'Fakaofo'],
			['id_pais' => 237, 'nombre' => 'Port of Spain'],
			['id_pais' => 241, 'nombre' => 'Mata-Utu'],
			['id_pais' => 89, 'nombre' => 'Amazonas'],
			['id_pais' => 89, 'nombre' => 'Ancash'],
			['id_pais' => 89, 'nombre' => 'Apurímac'],
			['id_pais' => 89, 'nombre' => 'Arequipa'],
			['id_pais' => 89, 'nombre' => 'Ayacucho'],
			['id_pais' => 89, 'nombre' => 'Cajamarca'],
			['id_pais' => 89, 'nombre' => 'Callao'],
			['id_pais' => 89, 'nombre' => 'Cusco'],
			['id_pais' => 89, 'nombre' => 'Huancavelica'],
			['id_pais' => 89, 'nombre' => 'Huánuco'],
			['id_pais' => 89, 'nombre' => 'Ica'],
			['id_pais' => 89, 'nombre' => 'Junín'],
			['id_pais' => 89, 'nombre' => 'La Libertad'],
			['id_pais' => 89, 'nombre' => 'Lambayeque'],
			['id_pais' => 89, 'nombre' => 'Lima'],
			['id_pais' => 89, 'nombre' => 'Loreto'],
			['id_pais' => 89, 'nombre' => 'Madre de Dios'],
			['id_pais' => 89, 'nombre' => 'Moquegua'],
			['id_pais' => 89, 'nombre' => 'Pasco'],
			['id_pais' => 89, 'nombre' => 'Piura'],
			['id_pais' => 89, 'nombre' => 'Puno'],
			['id_pais' => 89, 'nombre' => 'San Martín'],
			['id_pais' => 89, 'nombre' => 'Tacna'],
			['id_pais' => 89, 'nombre' => 'Tumbes'],
			['id_pais' => 89, 'nombre' => 'Ucayali'],
			['id_pais' => 110, 'nombre' => 'Alto Paraná'],
			['id_pais' => 110, 'nombre' => 'Amambay'],
			['id_pais' => 110, 'nombre' => 'Boquerón'],
			['id_pais' => 110, 'nombre' => 'Caaguazú'],
			['id_pais' => 110, 'nombre' => 'Caazapá'],
			['id_pais' => 110, 'nombre' => 'Central'],
			['id_pais' => 110, 'nombre' => 'Concepción'],
			['id_pais' => 110, 'nombre' => 'Cordillera'],
			['id_pais' => 110, 'nombre' => 'Guairá'],
			['id_pais' => 110, 'nombre' => 'Itapúa'],
			['id_pais' => 110, 'nombre' => 'Misiones'],
			['id_pais' => 110, 'nombre' => 'Neembucú'],
			['id_pais' => 110, 'nombre' => 'Paraguarí'],
			['id_pais' => 110, 'nombre' => 'Presidente Hayes'],
			['id_pais' => 110, 'nombre' => 'San Pedro'],
			['id_pais' => 110, 'nombre' => 'Alto Paraguay'],
			['id_pais' => 110, 'nombre' => 'Canindeyú'],
			['id_pais' => 110, 'nombre' => 'Chaco'],
			['id_pais' => 111, 'nombre' => 'Artigas'],
			['id_pais' => 111, 'nombre' => 'Canelones'],
			['id_pais' => 111, 'nombre' => 'Cerro Largo'],
			['id_pais' => 111, 'nombre' => 'Colonia'],
			['id_pais' => 111, 'nombre' => 'Durazno'],
			['id_pais' => 111, 'nombre' => 'Flores'],
			['id_pais' => 111, 'nombre' => 'Florida'],
			['id_pais' => 111, 'nombre' => 'Lavalleja'],
			['id_pais' => 111, 'nombre' => 'Maldonado'],
			['id_pais' => 111, 'nombre' => 'Montevideo'],
			['id_pais' => 111, 'nombre' => 'Paysandú'],
			['id_pais' => 111, 'nombre' => 'Río Negro'],
			['id_pais' => 111, 'nombre' => 'Rivera'],
			['id_pais' => 111, 'nombre' => 'Rocha'],
			['id_pais' => 111, 'nombre' => 'Salto'],
			['id_pais' => 111, 'nombre' => 'San José'],
			['id_pais' => 111, 'nombre' => 'Soriano'],
			['id_pais' => 111, 'nombre' => 'Tacuarembó'],
			['id_pais' => 111, 'nombre' => 'Treinta y Tres'],
			['id_pais' => 81, 'nombre' => 'Arica y Parinacota'],
			['id_pais' => 81, 'nombre' => 'Valparaíso'],
			['id_pais' => 81, 'nombre' => 'Aysén del General Carlos Ibáñez del Campo'],
			['id_pais' => 81, 'nombre' => 'Antofagasta'],
			['id_pais' => 81, 'nombre' => 'Araucanía'],
			['id_pais' => 81, 'nombre' => 'Atacama'],
			['id_pais' => 81, 'nombre' => 'Bío-Bío'],
			['id_pais' => 81, 'nombre' => 'Coquimbo'],
			['id_pais' => 81, 'nombre' => 'Libertador General Bernardo OHiggins'],
			['id_pais' => 81, 'nombre' => 'Los Lagos'],
			['id_pais' => 81, 'nombre' => 'Magallanes y de la Antártica Chilena'],
			['id_pais' => 81, 'nombre' => 'Maule'],
			['id_pais' => 81, 'nombre' => 'Region Metropolitana'],
			['id_pais' => 81, 'nombre' => 'Tarapacá'],
			['id_pais' => 185, 'nombre' => 'Alta Verapaz'],
			['id_pais' => 185, 'nombre' => 'Baja Verapaz'],
			['id_pais' => 185, 'nombre' => 'Chimaltenango'],
			['id_pais' => 185, 'nombre' => 'Chiquimula'],
			['id_pais' => 185, 'nombre' => 'El Progreso'],
			['id_pais' => 185, 'nombre' => 'Escuintla'],
			['id_pais' => 185, 'nombre' => 'Guatemala'],
			['id_pais' => 185, 'nombre' => 'Huehuetenango'],
			['id_pais' => 185, 'nombre' => 'Izabal'],
			['id_pais' => 185, 'nombre' => 'Jalapa'],
			['id_pais' => 185, 'nombre' => 'Jutiapa'],
			['id_pais' => 185, 'nombre' => 'Petén'],
			['id_pais' => 185, 'nombre' => 'Quetzaltenango'],
			['id_pais' => 185, 'nombre' => 'Quiché'],
			['id_pais' => 185, 'nombre' => 'Retalhuleu'],
			['id_pais' => 185, 'nombre' => 'Sacatepéquez'],
			['id_pais' => 185, 'nombre' => 'San Marcos'],
			['id_pais' => 185, 'nombre' => 'Santa Rosa'],
			['id_pais' => 185, 'nombre' => 'Sololá'],
			['id_pais' => 185, 'nombre' => 'Suchitepequez'],
			['id_pais' => 185, 'nombre' => 'Totonicapán'],
			['id_pais' => 185, 'nombre' => 'Zacapa'],
			['id_pais' => 82, 'nombre' => 'Amazonas'],
			['id_pais' => 82, 'nombre' => 'Antioquia'],
			['id_pais' => 82, 'nombre' => 'Arauca'],
			['id_pais' => 82, 'nombre' => 'Atlántico'],
			['id_pais' => 82, 'nombre' => 'Caquetá'],
			['id_pais' => 82, 'nombre' => 'Cauca'],
			['id_pais' => 82, 'nombre' => 'César'],
			['id_pais' => 82, 'nombre' => 'Chocó'],
			['id_pais' => 82, 'nombre' => 'Córdoba'],
			['id_pais' => 82, 'nombre' => 'Guaviare'],
			['id_pais' => 82, 'nombre' => 'Guainía'],
			['id_pais' => 82, 'nombre' => 'Huila'],
			['id_pais' => 82, 'nombre' => 'La Guajira'],
			['id_pais' => 82, 'nombre' => 'Meta'],
			['id_pais' => 82, 'nombre' => 'Narino'],
			['id_pais' => 82, 'nombre' => 'Norte de Santander'],
			['id_pais' => 82, 'nombre' => 'Putumayo'],
			['id_pais' => 82, 'nombre' => 'Quindío'],
			['id_pais' => 82, 'nombre' => 'Risaralda'],
			['id_pais' => 82, 'nombre' => 'San Andrés y Providencia'],
			['id_pais' => 82, 'nombre' => 'Santander'],
			['id_pais' => 82, 'nombre' => 'Sucre'],
			['id_pais' => 82, 'nombre' => 'Tolima'],
			['id_pais' => 82, 'nombre' => 'Valle del Cauca'],
			['id_pais' => 82, 'nombre' => 'Vaupés'],
			['id_pais' => 82, 'nombre' => 'Vichada'],
			['id_pais' => 82, 'nombre' => 'Casanare'],
			['id_pais' => 82, 'nombre' => 'Cundinamarca'],
			['id_pais' => 82, 'nombre' => 'Distrito Capital de Bogotá'],
			['id_pais' => 82, 'nombre' => 'Caldas'],
			['id_pais' => 82, 'nombre' => 'Magdalena'],
			['id_pais' => 42, 'nombre' => 'Aguascalientes'],
			['id_pais' => 42, 'nombre' => 'Baja California'],
			['id_pais' => 42, 'nombre' => 'Baja California Sur'],
			['id_pais' => 42, 'nombre' => 'Campeche'],
			['id_pais' => 42, 'nombre' => 'Chiapas'],
			['id_pais' => 42, 'nombre' => 'Chihuahua'],
			['id_pais' => 42, 'nombre' => 'Coahuila de Zaragoza'],
			['id_pais' => 42, 'nombre' => 'Colima'],
			['id_pais' => 42, 'nombre' => 'Distrito Federal'],
			['id_pais' => 42, 'nombre' => 'Durango'],
			['id_pais' => 42, 'nombre' => 'Guanajuato'],
			['id_pais' => 42, 'nombre' => 'Guerrero'],
			['id_pais' => 42, 'nombre' => 'Hidalgo'],
			['id_pais' => 42, 'nombre' => 'Jalisco'],
			['id_pais' => 42, 'nombre' => 'México'],
			['id_pais' => 42, 'nombre' => 'Michoacán de Ocampo'],
			['id_pais' => 42, 'nombre' => 'Morelos'],
			['id_pais' => 42, 'nombre' => 'Nayarit'],
			['id_pais' => 42, 'nombre' => 'Nuevo León'],
			['id_pais' => 42, 'nombre' => 'Oaxaca'],
			['id_pais' => 42, 'nombre' => 'Puebla'],
			['id_pais' => 42, 'nombre' => 'Querétaro de Arteaga'],
			['id_pais' => 42, 'nombre' => 'Quintana Roo'],
			['id_pais' => 42, 'nombre' => 'San Luis Potosí'],
			['id_pais' => 42, 'nombre' => 'Sinaloa'],
			['id_pais' => 42, 'nombre' => 'Sonora'],
			['id_pais' => 42, 'nombre' => 'Tabasco'],
			['id_pais' => 42, 'nombre' => 'Tamaulipas'],
			['id_pais' => 42, 'nombre' => 'Tlaxcala'],
			['id_pais' => 42, 'nombre' => 'Veracruz'],
			['id_pais' => 42, 'nombre' => 'Yucatán'],
			['id_pais' => 42, 'nombre' => 'Zacatecas'],
			['id_pais' => 124, 'nombre' => 'Bocas del Toro'],
			['id_pais' => 124, 'nombre' => 'Chiriquí'],
			['id_pais' => 124, 'nombre' => 'Coclé'],
			['id_pais' => 124, 'nombre' => 'Colón'],
			['id_pais' => 124, 'nombre' => 'Darién'],
			['id_pais' => 124, 'nombre' => 'Herrera'],
			['id_pais' => 124, 'nombre' => 'Los Santos'],
			['id_pais' => 124, 'nombre' => 'Panamá'],
			['id_pais' => 124, 'nombre' => 'San Blas'],
			['id_pais' => 124, 'nombre' => 'Veraguas'],
			['id_pais' => 123, 'nombre' => 'Chuquisaca'],
			['id_pais' => 123, 'nombre' => 'Cochabamba'],
			['id_pais' => 123, 'nombre' => 'El Beni'],
			['id_pais' => 123, 'nombre' => 'La Paz'],
			['id_pais' => 123, 'nombre' => 'Oruro'],
			['id_pais' => 123, 'nombre' => 'Pando'],
			['id_pais' => 123, 'nombre' => 'Potosí'],
			['id_pais' => 123, 'nombre' => 'Santa Cruz'],
			['id_pais' => 123, 'nombre' => 'Tarija'],
			['id_pais' => 36, 'nombre' => 'Alajuela'],
			['id_pais' => 36, 'nombre' => 'Cartago'],
			['id_pais' => 36, 'nombre' => 'Guanacaste'],
			['id_pais' => 36, 'nombre' => 'Heredia'],
			['id_pais' => 36, 'nombre' => 'Limón'],
			['id_pais' => 36, 'nombre' => 'Puntarenas'],
			['id_pais' => 36, 'nombre' => 'San José'],
			['id_pais' => 103, 'nombre' => 'Galápagos'],
			['id_pais' => 103, 'nombre' => 'Azuay'],
			['id_pais' => 103, 'nombre' => 'Bolívar'],
			['id_pais' => 103, 'nombre' => 'Canar'],
			['id_pais' => 103, 'nombre' => 'Carchi'],
			['id_pais' => 103, 'nombre' => 'Chimborazo'],
			['id_pais' => 103, 'nombre' => 'Cotopaxi'],
			['id_pais' => 103, 'nombre' => 'El Oro'],
			['id_pais' => 103, 'nombre' => 'Esmeraldas'],
			['id_pais' => 103, 'nombre' => 'Guayas'],
			['id_pais' => 103, 'nombre' => 'Imbabura'],
			['id_pais' => 103, 'nombre' => 'Loja'],
			['id_pais' => 103, 'nombre' => 'Los Ríos'],
			['id_pais' => 103, 'nombre' => 'Manabí'],
			['id_pais' => 103, 'nombre' => 'Morona-Santiago'],
			['id_pais' => 103, 'nombre' => 'Pastaza'],
			['id_pais' => 103, 'nombre' => 'Pichincha'],
			['id_pais' => 103, 'nombre' => 'Tungurahua'],
			['id_pais' => 103, 'nombre' => 'Zamora-Chinchipe'],
			['id_pais' => 103, 'nombre' => 'Sucumbíos'],
			['id_pais' => 103, 'nombre' => 'Napo'],
			['id_pais' => 103, 'nombre' => 'Orellana'],
			['id_pais' => 5, 'nombre' => 'Buenos Aires'],
			['id_pais' => 5, 'nombre' => 'Catamarca'],
			['id_pais' => 5, 'nombre' => 'Chaco'],
			['id_pais' => 5, 'nombre' => 'Chubut'],
			['id_pais' => 5, 'nombre' => 'Córdoba'],
			['id_pais' => 5, 'nombre' => 'Corrientes'],
			['id_pais' => 5, 'nombre' => 'Distrito Federal'],
			['id_pais' => 5, 'nombre' => 'Entre Ríos'],
			['id_pais' => 5, 'nombre' => 'Formosa'],
			['id_pais' => 5, 'nombre' => 'Jujuy'],
			['id_pais' => 5, 'nombre' => 'La Pampa'],
			['id_pais' => 5, 'nombre' => 'La Rioja'],
			['id_pais' => 5, 'nombre' => 'Mendoza'],
			['id_pais' => 5, 'nombre' => 'Misiones'],
			['id_pais' => 5, 'nombre' => 'Neuquén'],
			['id_pais' => 5, 'nombre' => 'Río Negro'],
			['id_pais' => 5, 'nombre' => 'Salta'],
			['id_pais' => 5, 'nombre' => 'San Juan'],
			['id_pais' => 5, 'nombre' => 'San Luis'],
			['id_pais' => 5, 'nombre' => 'Santa Cruz'],
			['id_pais' => 5, 'nombre' => 'Santa Fe'],
			['id_pais' => 5, 'nombre' => 'Santiago del Estero'],
			['id_pais' => 5, 'nombre' => 'Tierra del Fuego'],
			['id_pais' => 5, 'nombre' => 'Tucumán'],
			['id_pais' => 95, 'nombre' => 'Amazonas'],
			['id_pais' => 95, 'nombre' => 'Anzoategui'],
			['id_pais' => 95, 'nombre' => 'Apure'],
			['id_pais' => 95, 'nombre' => 'Aragua'],
			['id_pais' => 95, 'nombre' => 'Barinas'],
			['id_pais' => 95, 'nombre' => 'Bolívar'],
			['id_pais' => 95, 'nombre' => 'Carabobo'],
			['id_pais' => 95, 'nombre' => 'Cojedes'],
			['id_pais' => 95, 'nombre' => 'Delta Amacuro'],
			['id_pais' => 95, 'nombre' => 'Falcón'],
			['id_pais' => 95, 'nombre' => 'Guárico'],
			['id_pais' => 95, 'nombre' => 'Lara'],
			['id_pais' => 95, 'nombre' => 'Mérida'],
			['id_pais' => 95, 'nombre' => 'Miranda'],
			['id_pais' => 95, 'nombre' => 'Monagas'],
			['id_pais' => 95, 'nombre' => 'Nueva Esparta'],
			['id_pais' => 95, 'nombre' => 'Portuguesa'],
			['id_pais' => 95, 'nombre' => 'Sucre'],
			['id_pais' => 95, 'nombre' => 'Táchira'],
			['id_pais' => 95, 'nombre' => 'Trujillo'],
			['id_pais' => 95, 'nombre' => 'Yaracuy'],
			['id_pais' => 95, 'nombre' => 'Zulia'],
			['id_pais' => 95, 'nombre' => 'Dependencias Federales'],
			['id_pais' => 95, 'nombre' => 'Distrito Federal'],
			['id_pais' => 95, 'nombre' => 'Vargas'],
			['id_pais' => 209, 'nombre' => 'Boaco'],
			['id_pais' => 209, 'nombre' => 'Carazo'],
			['id_pais' => 209, 'nombre' => 'Chinandega'],
			['id_pais' => 209, 'nombre' => 'Chontales'],
			['id_pais' => 209, 'nombre' => 'Estelí'],
			['id_pais' => 209, 'nombre' => 'Granada'],
			['id_pais' => 209, 'nombre' => 'Jinotega'],
			['id_pais' => 209, 'nombre' => 'León'],
			['id_pais' => 209, 'nombre' => 'Madriz'],
			['id_pais' => 209, 'nombre' => 'Managua'],
			['id_pais' => 209, 'nombre' => 'Masaya'],
			['id_pais' => 209, 'nombre' => 'Matagalpa'],
			['id_pais' => 209, 'nombre' => 'Nueva Segovia'],
			['id_pais' => 209, 'nombre' => 'Rio San Juan'],
			['id_pais' => 209, 'nombre' => 'Rivas'],
			['id_pais' => 209, 'nombre' => 'Zelaya'],
			['id_pais' => 113, 'nombre' => 'Pinar del Rio'],
			['id_pais' => 113, 'nombre' => 'Ciudad de la Habana'],
			['id_pais' => 113, 'nombre' => 'Matanzas'],
			['id_pais' => 113, 'nombre' => 'Isla de la Juventud'],
			['id_pais' => 113, 'nombre' => 'Camaguey'],
			['id_pais' => 113, 'nombre' => 'Ciego de Avila'],
			['id_pais' => 113, 'nombre' => 'Cienfuegos'],
			['id_pais' => 113, 'nombre' => 'Granma'],
			['id_pais' => 113, 'nombre' => 'Guantanamo'],
			['id_pais' => 113, 'nombre' => 'La Habana'],
			['id_pais' => 113, 'nombre' => 'Holguin'],
			['id_pais' => 113, 'nombre' => 'Las Tunas'],
			['id_pais' => 113, 'nombre' => 'Sancti Spiritus'],
			['id_pais' => 113, 'nombre' => 'Santiago de Cuba'],
			['id_pais' => 113, 'nombre' => 'Villa Clara'],
			['id_pais' => 12, 'nombre' => 'Acre'],
			['id_pais' => 12, 'nombre' => 'Alagoas'],
			['id_pais' => 12, 'nombre' => 'Amapa'],
			['id_pais' => 12, 'nombre' => 'Amazonas'],
			['id_pais' => 12, 'nombre' => 'Bahia'],
			['id_pais' => 12, 'nombre' => 'Ceara'],
			['id_pais' => 12, 'nombre' => 'Distrito Federal'],
			['id_pais' => 12, 'nombre' => 'Espirito Santo'],
			['id_pais' => 12, 'nombre' => 'Mato Grosso do Sul'],
			['id_pais' => 12, 'nombre' => 'Maranhao'],
			['id_pais' => 12, 'nombre' => 'Mato Grosso'],
			['id_pais' => 12, 'nombre' => 'Minas Gerais'],
			['id_pais' => 12, 'nombre' => 'Para'],
			['id_pais' => 12, 'nombre' => 'Paraiba'],
			['id_pais' => 12, 'nombre' => 'Parana'],
			['id_pais' => 12, 'nombre' => 'Piaui'],
			['id_pais' => 12, 'nombre' => 'Rio de Janeiro'],
			['id_pais' => 12, 'nombre' => 'Rio Grande do Norte'],
			['id_pais' => 12, 'nombre' => 'Rio Grande do Sul'],
			['id_pais' => 12, 'nombre' => 'Rondonia'],
			['id_pais' => 12, 'nombre' => 'Roraima'],
			['id_pais' => 12, 'nombre' => 'Santa Catarina'],
			['id_pais' => 12, 'nombre' => 'Sao Paulo'],
			['id_pais' => 12, 'nombre' => 'Sergipe'],
			['id_pais' => 12, 'nombre' => 'Goias'],
			['id_pais' => 12, 'nombre' => 'Pernambuco'],
			['id_pais' => 12, 'nombre' => 'Tocantins'],
			['id_pais' => 83, 'nombre' => 'Akureyri'],
			['id_pais' => 83, 'nombre' => 'Arnessysla'],
			['id_pais' => 83, 'nombre' => 'Austur-Bardastrandarsysla'],
			['id_pais' => 83, 'nombre' => 'Austur-Hunavatnssysla'],
			['id_pais' => 83, 'nombre' => 'Austur-Skaftafellssysla'],
			['id_pais' => 83, 'nombre' => 'Borgarfjardarsysla'],
			['id_pais' => 83, 'nombre' => 'Dalasysla'],
			['id_pais' => 83, 'nombre' => 'Eyjafjardarsysla'],
			['id_pais' => 83, 'nombre' => 'Gullbringusysla'],
			['id_pais' => 83, 'nombre' => 'Hafnarfjordur'],
			['id_pais' => 83, 'nombre' => 'Kjosarsysla'],
			['id_pais' => 83, 'nombre' => 'Kopavogur'],
			['id_pais' => 83, 'nombre' => 'Myrasysla'],
			['id_pais' => 83, 'nombre' => 'Neskaupstadur'],
			['id_pais' => 83, 'nombre' => 'Nordur-Isafjardarsysla'],
			['id_pais' => 83, 'nombre' => 'Nordur-Mulasysla'],
			['id_pais' => 83, 'nombre' => 'Nordur-Tingeyjarsysla'],
			['id_pais' => 83, 'nombre' => 'Olafsfjordur'],
			['id_pais' => 83, 'nombre' => 'Rangarvallasysla'],
			['id_pais' => 83, 'nombre' => 'Reykjavik'],
			['id_pais' => 83, 'nombre' => 'Saudarkrokur'],
			['id_pais' => 83, 'nombre' => 'Seydisfjordur'],
			['id_pais' => 83, 'nombre' => 'Skagafjardarsysla'],
			['id_pais' => 83, 'nombre' => 'Snafellsnes- og Hnappadalssysla'],
			['id_pais' => 83, 'nombre' => 'Strandasysla'],
			['id_pais' => 83, 'nombre' => 'Sudur-Mulasysla'],
			['id_pais' => 83, 'nombre' => 'Sudur-Tingeyjarsysla'],
			['id_pais' => 83, 'nombre' => 'Vestmannaeyjar'],
			['id_pais' => 83, 'nombre' => 'Vestur-Bardastrandarsysla'],
			['id_pais' => 83, 'nombre' => 'Vestur-Isafjardarsysla'],
			['id_pais' => 83, 'nombre' => 'Vestur-Skaftafellssysla'],
			['id_pais' => 35, 'nombre' => 'Anhui'],
			['id_pais' => 35, 'nombre' => 'Zhejiang'],
			['id_pais' => 35, 'nombre' => 'Jiangxi'],
			['id_pais' => 35, 'nombre' => 'Jiangsu'],
			['id_pais' => 35, 'nombre' => 'Jilin'],
			['id_pais' => 35, 'nombre' => 'Qinghai'],
			['id_pais' => 35, 'nombre' => 'Fujian'],
			['id_pais' => 35, 'nombre' => 'Heilongjiang'],
			['id_pais' => 35, 'nombre' => 'Henan'],
			['id_pais' => 35, 'nombre' => 'Hebei'],
			['id_pais' => 35, 'nombre' => 'Hunan'],
			['id_pais' => 35, 'nombre' => 'Hubei'],
			['id_pais' => 35, 'nombre' => 'Xinjiang'],
			['id_pais' => 35, 'nombre' => 'Xizang'],
			['id_pais' => 35, 'nombre' => 'Gansu'],
			['id_pais' => 35, 'nombre' => 'Guangxi'],
			['id_pais' => 35, 'nombre' => 'Guizhou'],
			['id_pais' => 35, 'nombre' => 'Liaoning'],
			['id_pais' => 35, 'nombre' => 'Nei Mongol'],
			['id_pais' => 35, 'nombre' => 'Ningxia'],
			['id_pais' => 35, 'nombre' => 'Beijing'],
			['id_pais' => 35, 'nombre' => 'Shanghai'],
			['id_pais' => 35, 'nombre' => 'Shanxi'],
			['id_pais' => 35, 'nombre' => 'Shandong'],
			['id_pais' => 35, 'nombre' => 'Shaanxi'],
			['id_pais' => 35, 'nombre' => 'Sichuan'],
			['id_pais' => 35, 'nombre' => 'Tianjin'],
			['id_pais' => 35, 'nombre' => 'Yunnan'],
			['id_pais' => 35, 'nombre' => 'Guangdong'],
			['id_pais' => 35, 'nombre' => 'Hainan'],
			['id_pais' => 35, 'nombre' => 'Chongqing'],
			['id_pais' => 97, 'nombre' => 'Central'],
			['id_pais' => 97, 'nombre' => 'Coast'],
			['id_pais' => 97, 'nombre' => 'Eastern'],
			['id_pais' => 97, 'nombre' => 'Nairobi Area'],
			['id_pais' => 97, 'nombre' => 'North-Eastern'],
			['id_pais' => 97, 'nombre' => 'Nyanza'],
			['id_pais' => 97, 'nombre' => 'Rift Valley'],
			['id_pais' => 97, 'nombre' => 'Western'],
			['id_pais' => 195, 'nombre' => 'Gilbert Islands'],
			['id_pais' => 195, 'nombre' => 'Line Islands'],
			['id_pais' => 195, 'nombre' => 'Phoenix Islands'],
			['id_pais' => 1, 'nombre' => 'Australian Capital Territory'],
			['id_pais' => 1, 'nombre' => 'New South Wales'],
			['id_pais' => 1, 'nombre' => 'Northern Territory'],
			['id_pais' => 1, 'nombre' => 'Queensland'],
			['id_pais' => 1, 'nombre' => 'South Australia'],
			['id_pais' => 1, 'nombre' => 'Tasmania'],
			['id_pais' => 1, 'nombre' => 'Victoria'],
			['id_pais' => 1, 'nombre' => 'Western Australia'],
			['id_pais' => 27, 'nombre' => 'Dublin'],
			['id_pais' => 27, 'nombre' => 'Galway'],
			['id_pais' => 27, 'nombre' => 'Kildare'],
			['id_pais' => 27, 'nombre' => 'Leitrim'],
			['id_pais' => 27, 'nombre' => 'Limerick'],
			['id_pais' => 27, 'nombre' => 'Mayo'],
			['id_pais' => 27, 'nombre' => 'Meath'],
			['id_pais' => 27, 'nombre' => 'Carlow'],
			['id_pais' => 27, 'nombre' => 'Kilkenny'],
			['id_pais' => 27, 'nombre' => 'Laois'],
			['id_pais' => 27, 'nombre' => 'Longford'],
			['id_pais' => 27, 'nombre' => 'Louth'],
			['id_pais' => 27, 'nombre' => 'Offaly'],
			['id_pais' => 27, 'nombre' => 'Westmeath'],
			['id_pais' => 27, 'nombre' => 'Wexford'],
			['id_pais' => 27, 'nombre' => 'Wicklow'],
			['id_pais' => 27, 'nombre' => 'Roscommon'],
			['id_pais' => 27, 'nombre' => 'Sligo'],
			['id_pais' => 27, 'nombre' => 'Clare'],
			['id_pais' => 27, 'nombre' => 'Cork'],
			['id_pais' => 27, 'nombre' => 'Kerry'],
			['id_pais' => 27, 'nombre' => 'Tipperary'],
			['id_pais' => 27, 'nombre' => 'Waterford'],
			['id_pais' => 27, 'nombre' => 'Cavan'],
			['id_pais' => 27, 'nombre' => 'Donegal'],
			['id_pais' => 27, 'nombre' => 'Monaghan'],
			['id_pais' => 50, 'nombre' => 'Karachaeva-Cherkesskaya Respublica'],
			['id_pais' => 50, 'nombre' => 'Raimirskii (Dolgano-Nenetskii) AO'],
			['id_pais' => 50, 'nombre' => 'Respublica Tiva'],
			['id_pais' => 32, 'nombre' => 'Newfoundland'],
			['id_pais' => 32, 'nombre' => 'Nova Scotia'],
			['id_pais' => 32, 'nombre' => 'Prince Edward Island'],
			['id_pais' => 32, 'nombre' => 'New Brunswick'],
			['id_pais' => 32, 'nombre' => 'Quebec'],
			['id_pais' => 32, 'nombre' => 'Ontario'],
			['id_pais' => 32, 'nombre' => 'Manitoba'],
			['id_pais' => 32, 'nombre' => 'Saskatchewan'],
			['id_pais' => 32, 'nombre' => 'Alberta'],
			['id_pais' => 32, 'nombre' => 'British Columbia'],
			['id_pais' => 32, 'nombre' => 'Nunavut'],
			['id_pais' => 32, 'nombre' => 'Northwest Territories'],
			['id_pais' => 32, 'nombre' => 'Yukon Territory'],
			['id_pais' => 19, 'nombre' => 'Drenthe'],
			['id_pais' => 19, 'nombre' => 'Friesland'],
			['id_pais' => 19, 'nombre' => 'Gelderland'],
			['id_pais' => 19, 'nombre' => 'Groningen'],
			['id_pais' => 19, 'nombre' => 'Limburg'],
			['id_pais' => 19, 'nombre' => 'Noord-Brabant'],
			['id_pais' => 19, 'nombre' => 'Noord-Holland'],
			['id_pais' => 19, 'nombre' => 'Utrecht'],
			['id_pais' => 19, 'nombre' => 'Zeeland'],
			['id_pais' => 19, 'nombre' => 'Zuid-Holland'],
			['id_pais' => 19, 'nombre' => 'Overijssel'],
			['id_pais' => 19, 'nombre' => 'Flevoland'],
			['id_pais' => 138, 'nombre' => 'Duarte'],
			['id_pais' => 138, 'nombre' => 'Puerto Plata'],
			['id_pais' => 138, 'nombre' => 'Valverde'],
			['id_pais' => 138, 'nombre' => 'María Trinidad Sánchez'],
			['id_pais' => 138, 'nombre' => 'Azua'],
			['id_pais' => 138, 'nombre' => 'Santiago'],
			['id_pais' => 138, 'nombre' => 'San Cristóbal'],
			['id_pais' => 138, 'nombre' => 'Peravia'],
			['id_pais' => 138, 'nombre' => 'Elías Piña'],
			['id_pais' => 138, 'nombre' => 'Barahona'],
			['id_pais' => 138, 'nombre' => 'Monte Plata'],
			['id_pais' => 138, 'nombre' => 'Hermanas Mirabal'],
			['id_pais' => 138, 'nombre' => 'La Altagracia'],
			['id_pais' => 138, 'nombre' => 'San Juan'],
			['id_pais' => 138, 'nombre' => 'Monseñor Nouel'],
			['id_pais' => 138, 'nombre' => 'Monte Cristi'],
			['id_pais' => 138, 'nombre' => 'Espaillat'],
			['id_pais' => 138, 'nombre' => 'Sánchez Ramírez'],
			['id_pais' => 138, 'nombre' => 'La Vega'],
			['id_pais' => 138, 'nombre' => 'San Pedro de Macorís'],
			['id_pais' => 138, 'nombre' => 'Independencia'],
			['id_pais' => 138, 'nombre' => 'Dajabón'],
			['id_pais' => 138, 'nombre' => 'Bahoruco'],
			['id_pais' => 138, 'nombre' => 'El Seibo'],
			['id_pais' => 138, 'nombre' => 'Hato Mayor'],
			['id_pais' => 138, 'nombre' => 'La Romana'],
			['id_pais' => 138, 'nombre' => 'Pedernales'],
			['id_pais' => 138, 'nombre' => 'Samaná'],
			['id_pais' => 138, 'nombre' => 'Santiago Rodríguez'],
			['id_pais' => 138, 'nombre' => 'San José de Ocoa'],
			['id_pais' => 70, 'nombre' => 'Chiba'],
			['id_pais' => 70, 'nombre' => 'Ehime'],
			['id_pais' => 70, 'nombre' => 'Oita'],
			['id_pais' => 85, 'nombre' => 'Skopje'],
			['id_pais' => 35, 'nombre' => 'Schanghai'],
			['id_pais' => 35, 'nombre' => 'Hongkong'],
			['id_pais' => 35, 'nombre' => 'Neimenggu'],
			['id_pais' => 35, 'nombre' => 'Aomen'],
			['id_pais' => 92, 'nombre' => 'Amnat Charoen'],
			['id_pais' => 92, 'nombre' => 'Ang Thong'],
			['id_pais' => 92, 'nombre' => 'Bangkok'],
			['id_pais' => 92, 'nombre' => 'Buri Ram'],
			['id_pais' => 92, 'nombre' => 'Chachoengsao'],
			['id_pais' => 92, 'nombre' => 'Chai Nat'],
			['id_pais' => 92, 'nombre' => 'Chaiyaphum'],
			['id_pais' => 92, 'nombre' => 'Chanthaburi'],
			['id_pais' => 92, 'nombre' => 'Chiang Mai'],
			['id_pais' => 92, 'nombre' => 'Chiang Rai'],
			['id_pais' => 92, 'nombre' => 'Chon Buri'],
			['id_pais' => 92, 'nombre' => 'Kalasin'],
			['id_pais' => 92, 'nombre' => 'Kanchanaburi'],
			['id_pais' => 92, 'nombre' => 'Khon Kaen'],
			['id_pais' => 92, 'nombre' => 'Krabi'],
			['id_pais' => 92, 'nombre' => 'Lampang'],
			['id_pais' => 92, 'nombre' => 'Loei'],
			['id_pais' => 92, 'nombre' => 'Lop Buri'],
			['id_pais' => 92, 'nombre' => 'Mae Hong Son'],
			['id_pais' => 92, 'nombre' => 'Maha Sarakham'],
			['id_pais' => 92, 'nombre' => 'Nakhon Pathom'],
			['id_pais' => 92, 'nombre' => 'Nakhon Ratchasima'],
			['id_pais' => 92, 'nombre' => 'Nakhon Sawan'],
			['id_pais' => 92, 'nombre' => 'Nakhon Si Thammarat'],
			['id_pais' => 92, 'nombre' => 'Narathiwat'],
			['id_pais' => 92, 'nombre' => 'Nong Bua Lam Phu'],
			['id_pais' => 92, 'nombre' => 'Nong Khai'],
			['id_pais' => 92, 'nombre' => 'Nonthaburi'],
			['id_pais' => 92, 'nombre' => 'Pathum Thani'],
			['id_pais' => 92, 'nombre' => 'Pattani'],
			['id_pais' => 92, 'nombre' => 'Phangnga'],
			['id_pais' => 92, 'nombre' => 'Phatthalung'],
			['id_pais' => 92, 'nombre' => 'Phichit'],
			['id_pais' => 92, 'nombre' => 'Phitsanulok'],
			['id_pais' => 92, 'nombre' => 'Phra Nakhon Si Ayutthaya'],
			['id_pais' => 92, 'nombre' => 'Phrae'],
			['id_pais' => 92, 'nombre' => 'Phuket'],
			['id_pais' => 92, 'nombre' => 'Prachin Buri'],
			['id_pais' => 92, 'nombre' => 'Prachuap Khiri Khan'],
			['id_pais' => 92, 'nombre' => 'Ratchaburi'],
			['id_pais' => 92, 'nombre' => 'Rayong'],
			['id_pais' => 92, 'nombre' => 'Roi Et'],
			['id_pais' => 92, 'nombre' => 'Sa Kaeo'],
			['id_pais' => 92, 'nombre' => 'Sakon Nakhon'],
			['id_pais' => 92, 'nombre' => 'Samut Prakan'],
			['id_pais' => 92, 'nombre' => 'Samut Sakhon'],
			['id_pais' => 92, 'nombre' => 'Samut Songkhran'],
			['id_pais' => 92, 'nombre' => 'Saraburi'],
			['id_pais' => 92, 'nombre' => 'Si Sa Ket'],
			['id_pais' => 92, 'nombre' => 'Sing Buri'],
			['id_pais' => 92, 'nombre' => 'Songkhla'],
			['id_pais' => 92, 'nombre' => 'Sukhothai'],
			['id_pais' => 92, 'nombre' => 'Suphan Buri'],
			['id_pais' => 92, 'nombre' => 'Surat Thani'],
			['id_pais' => 92, 'nombre' => 'Surin'],
			['id_pais' => 92, 'nombre' => 'Trang'],
			['id_pais' => 92, 'nombre' => 'Ubon Ratchathani'],
			['id_pais' => 92, 'nombre' => 'Udon Thani'],
			['id_pais' => 92, 'nombre' => 'Uthai Thani'],
			['id_pais' => 92, 'nombre' => 'Uttaradit'],
			['id_pais' => 92, 'nombre' => 'Yala'],
			['id_pais' => 92, 'nombre' => 'Yasothon'],
			['id_pais' => 69, 'nombre' => 'Busan'],
			['id_pais' => 69, 'nombre' => 'Daegu'],
			['id_pais' => 69, 'nombre' => 'Gangwon'],
			['id_pais' => 69, 'nombre' => 'Gwangju'],
			['id_pais' => 69, 'nombre' => 'Gyeonggi'],
			['id_pais' => 69, 'nombre' => 'Gyeongsangbuk'],
			['id_pais' => 69, 'nombre' => 'Gyeongsangnam'],
			['id_pais' => 69, 'nombre' => 'Jeju'],
			['id_pais' => 25, 'nombre' => 'Delhi'],
			['id_pais' => 82, 'nombre' => 'Bolivar'],
			['id_pais' => 82, 'nombre' => 'Boyacá'],
			['id_pais' => 138, 'nombre' => 'Distrito Nacional']
        ], null, 50);

		// $estados_insertados = $estados);

		if (!$estados_insertados) {
			echo "****Estados NO insertados****\n";
			return;
		}
	}
}